### ISSUE TITLE
Getting exception in Tax Rate API

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#100]
Description -

In the Settings -> Tax Rate API ->

**Create New Tax Rate API -** 

**Update TaxRate Details API -**
we are unable to create the tax rate without giving the iszip code value.

**Screenshot -**
![Screenshot from 2023-11-23 15-38-54](https://github.com/bagisto/headless-ecommerce/assets/126852181/f1f2a190-2fef-4010-9f21-117abcf50f4a)

**Remove Tax Rate API -**

If we give the inventory ID [which does not exist] then we get an internal server error but need to get the proper message data not found on the console.

**Screenshot -**

![Screenshot from 2023-11-23 15-43-53](https://github.com/bagisto/headless-ecommerce/assets/126852181/37dde5d0-0ddb-4746-9e26-30a2b14ae50d)

**Comment by rachana-webkul** [comment]
@mukulsharma-webkul  **we are unable to create the tax rate without giving the iszip code value.** issue fixed. Other issues are invalid

**Comment by mukulsharma-webkul** [comment]
tested, for Create New Tax Rate API, we are able to create tax rate, 

**Screenshot -**

![Screenshot from 2023-11-27 13-27-08](https://github.com/bagisto/headless-ecommerce/assets/126852181/bb6575f5-c6ff-4c54-b877-66087a1bb408)

Remove Tax Rate API -
we need to give correct data only to remove the tax rate.

So, I am closing the issue.
