### ISSUE TITLE
Getting exception in TaxCategory API

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#101]
Description -

In the Settings -> Tax Categories API ->

**Get Tax Category Details API -**

When we want to get the Tax Category -> While hitting API we get an exception.

**Create New TaxCategory API -**

If we create the TaxCategory [which is already created] then getting internal server error exception, but need to get the proper message Tax Category already created.

**Screenshot -**

![Screenshot from 2023-11-23 16-57-13](https://github.com/bagisto/headless-ecommerce/assets/126852181/cd2eb2db-8886-4ceb-8af8-fb6e51815481)

**Update TaxCategory Details API -**

If we update the TaxCategory [which is not exist] then getting internal server error, need to get the proper message TaxCategory not found

**Screenshot -**
![Screenshot from 2023-11-23 17-01-03](https://github.com/bagisto/headless-ecommerce/assets/126852181/2a7456c5-25e2-42eb-bca2-36dc2a48efe8)

**Remove TaxCategory API -**

Unable to delete the TaxCategory API 
**Screenshot -**

![Screenshot from 2023-11-23 17-01-50](https://github.com/bagisto/headless-ecommerce/assets/126852181/a544fb45-a69d-409e-8121-218364a63648)

**Comment by rachana-webkul** [comment]
@mukulsharma-webkul  for the issue:-**Unable to delete the TaxCategory API** ,just send Authorization as Bearer Token

**Comment by mukulsharma-webkul** [comment]
tested, able to do operations on TaxCategories API, GetTaxCategory, Remove TaxCategory , so I am closing the issue.

**Screenshot -**

![Screenshot from 2023-11-27 13-44-15](https://github.com/bagisto/headless-ecommerce/assets/126852181/3b714487-4ce3-4104-ba9c-f841a43e5114)
