### ISSUE TITLE
Getting exception in the Theme API

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#103]
Description -

**Create Theme API -** 

**Update Theme API -**

In the Theme API -> Create Theme API - By hitting the API, the Theme is created but on the admin panel, the theme is not showing.
this issue is happing both create and update API

**Video -**

https://github.com/bagisto/headless-ecommerce/assets/126852181/9d0b4242-c9cc-44b3-b8e3-f1592d42d790

**Remove Theme API -**

While deleting the Theme by id, getting exception.

**Screenshot -**

![Screenshot from 2023-11-23 18-34-54](https://github.com/bagisto/headless-ecommerce/assets/126852181/b12ba208-af4b-48af-907c-8a61ec47769b)

**Comment by rachana-webkul** [comment]
@mukulsharma-webkul theme will visible after you edit the theme. It's not an issue
