### ISSUE TITLE
Please change API method to GET 

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#104]
Description -

In the Countries API -

Get All Country List API
Get Country Details
Get CountryStates List 

Please change API method to Get API. Because we are not send any request data data, we only getting the data.

**Screenshot -**

![Screenshot from 2023-11-23 18-38-19](https://github.com/bagisto/headless-ecommerce/assets/126852181/1bf7951e-e654-4cc6-9591-4dbf5f5d9470)

**Comment by rachana-webkul** [comment]
@mukulsharma-webkul  it's the GraphQL syntax .It is not an issue
