### ISSUE TITLE
Getting exception on Config Product API

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#106]
Description -

**Create Config Product API -**
While creating the Config Product if created the product [already created product] then getting internal server exception, but get only the message product already created.

**Update Config Product API -**

Unable to update the product, getting 500 internal server exception.

**Screenshot -**

![Screenshot from 2023-11-23 19-26-43](https://github.com/bagisto/headless-ecommerce/assets/126852181/065efe84-d5c2-4daa-927f-bf54fc928a04)

**Comment by rachana-webkul** [comment]
@mukulsharma-webkul  working fine. Pass correct data in each field

**Comment by mukulsharma-webkul** [comment]
tested, now able to Create/Update the Config Product, so I am closing the issue.

**Screenshot -**

![Screenshot from 2023-11-27 16-53-10](https://github.com/bagisto/headless-ecommerce/assets/126852181/81fa799c-a566-4287-aa36-5576cebd2a0d)
