### ISSUE TITLE
Getting exception in Update Group Product

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#107]
Description -

**Create Virtual Product API -**
While creating the Virtual Product if created the product [already created product] then getting intertnal server exception, but gets only message product already created.

***Create Group Product API -**
While creating the Group Product if created the product [already created product] then getting internal server exception, but getting only message product already created.

**Screenshot -**
![Screenshot from 2023-11-23 19-33-47](https://github.com/bagisto/headless-ecommerce/assets/126852181/75e04436-80e1-44ee-9d73-c597aa717107)

**Update Group Product API -**

Unable to update the Group Product API, gettiing 500 internal server exception.

**Screenshot -**

![Screenshot from 2023-11-23 19-35-29](https://github.com/bagisto/headless-ecommerce/assets/126852181/1c403a09-59ef-4fa5-a0bb-cb63376b061d)

**Comment by rachana-webkul** [comment]
@mukulsharma-webkul  working fine

**Comment by mukulsharma-webkul** [comment]
tested, able to Update Group Product, so I am closing the issue.

**Screenshot -**

![Screenshot from 2023-11-27 15-37-24](https://github.com/bagisto/headless-ecommerce/assets/126852181/917263d5-3589-4d66-842a-7d3bd80080c5)
