### ISSUE TITLE
Getting exception in Downloadable Product API 

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#108]
Description -

**Create Download Product API -**
While creating the Download Product if created the product [already created product] then getting internal server exception, but getting only message product already created.

**Update Downloadable Product API -**
While Updating the Download Product [already updated product] then getting internal server exception, but getting only message product already updated.

**Screenshot -**

![Screenshot from 2023-11-23 19-59-08](https://github.com/bagisto/headless-ecommerce/assets/126852181/4981fe4f-dc48-4829-9d47-c080920d1cd7)

**Comment by rachana-webkul** [comment]
@mukulsharma-webkul working fine
