### ISSUE TITLE
Getting exception in Categories API 

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#109]
**Description -**

Catalog -> Categories -> Create New Category API 

While Hitting the Create New Category API the category is created on the admin panel but getting internal server error on the Postman.

**Video -**

https://github.com/bagisto/headless-ecommerce/assets/126852181/95f052a0-fb3f-44aa-8796-2ce0437989fd

**Screenshot -**

![Screenshot from 2023-11-24 08-57-27](https://github.com/bagisto/headless-ecommerce/assets/126852181/a4c1259f-7ee2-4701-b8d5-83d86988bbbb)

**Update Category Details API -**

1) While updating the Category getting an internal server error

2) While updating the category giving id[which does not exist] getting an exception, need to get message Category does not exist.

**Screenshot -**

![Screenshot from 2023-11-24 09-13-13](https://github.com/bagisto/headless-ecommerce/assets/126852181/f48bc7da-734e-42c6-b933-a65eb25f1152)

**Comment by rachana-webkul** [comment]
@mukulsharma-webkul pass correct attribute id,it will work fine

**Comment by mukulsharma-webkul** [comment]
tested, Create/Update Categories API is working fine, so I am closing the issue.

**Screenshot -**

![Screenshot from 2023-11-27 16-44-08](https://github.com/bagisto/headless-ecommerce/assets/126852181/88f56056-5944-4e88-905d-db218f9bb6c7)
