### ISSUE TITLE
Getting issue in Get and Post CMS Page API

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#111]
**Description -**

CMS API -

**Get All CMS Page LIst API -**
 
While hitting get all CMS Page API, all the list of CMS pages are not showing.
It is showing 10 CMS pages.
But we have 12 CMS pages.

**Screenshot -**
![Screenshot from 2023-11-24 11-13-41](https://github.com/bagisto/headless-ecommerce/assets/126852181/b1a7d582-2542-4041-80b7-13e962288e49)

**CMS Pages on Admin Panel -**

![Screenshot from 2023-11-24 11-14-22](https://github.com/bagisto/headless-ecommerce/assets/126852181/b5c74c2e-be10-4af9-b570-08cb530be1f8)

**Update CMS Page API -**

While hitting the update API, it is not update the CMS Page, while check on the admin panel, CMS Page is not updated.

**Screenshot of Postman -**
![Screenshot from 2023-11-24 11-15-36](https://github.com/bagisto/headless-ecommerce/assets/126852181/828a6043-a92d-4194-95c8-effe1218210f)

**Screenshot of Admin Panel -**

![Screenshot from 2023-11-24 11-32-03](https://github.com/bagisto/headless-ecommerce/assets/126852181/9714f80d-77fd-454a-9438-84eecbf10fea)

**Comment by rachana-webkul** [comment]
@mukulsharma-webkul for issue **While hitting get all CMS Page API, all the list of CMS pages are not showing.** it is fixed 
and for second issue **While hitting the update API, it is not update the CMS Page, while check on the admin panel, CMS Page is not updated.** it is getting updated based on locale

**Comment by mukulsharma-webkul** [comment]
tested, now the listing of all the CMS Pages is showing, so I am closing the issue.

**Screenshot -**

![Screenshot from 2023-11-28 12-43-37](https://github.com/bagisto/headless-ecommerce/assets/126852181/e6382242-8abc-4cab-a224-338b41cbc175)
