### ISSUE TITLE
Getting issue in Shop -> Products API

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#116]
**Description -**

Shop -> Products ->

**Get Slider Details API -**

While hitting the Get Slider Details API, getting the below message.

**Screenshot -**

![Screenshot from 2023-11-24 20-16-29](https://github.com/bagisto/headless-ecommerce/assets/126852181/4bf24b07-df4e-4089-b802-bb071e423764)

Sales -> Shipment API 

**Screenshot -**

![Screenshot from 2023-11-28 13-15-10](https://github.com/bagisto/headless-ecommerce/assets/126852181/d44189a4-a2ae-421c-a721-9fb1c5df1335)

**Comment by rachana-webkul** [comment]
@mukulsharma-webkul  In Bagisto v2.0.0 there is no need of **slider api** as the functionality is removed from Bagisto
