### ISSUE TITLE
Webkul\\CMS\\MOdels\\CmsPageTranslation

### ISSUE THREAD

**Issue by AdolphYu** [bagisto/headless-ecommerce#132]
change Webkul\\CMS\\Models\\CmsPageTranslation in \src\graphql\cms\cms_page.graphql

**Comment by vivek-webkul** [comment]
@Anmol-Chauhan

**Comment by Anmol-Chauhan** [comment]
Rename Webkul\\CMS\\MOdels\\CmsPageTranslation
to Webkul\\CMS\\Models\\CmsPageTranslation
