### ISSUE TITLE
Installation problem with PHP 8.3.2

### ISSUE THREAD

**Issue by jbohme** [bagisto/headless-ecommerce#135]
When trying to install with composer `composer require bagisto/graphql-api dev-main` an error is returned:

![image](https://github.com/bagisto/headless-ecommerce/assets/32618269/8d15d0f4-5351-4fa4-861f-c0e6479b0739)

Declaring the return in the function solves the problem:

![image](https://github.com/bagisto/headless-ecommerce/assets/32618269/800e771d-b73a-445d-93a5-09ea7f73b31b)

**Comment by karan-nukani** [comment]
same error I got in PHP: 8.2.12..

**Comment by Anmol-Chauhan** [comment]
The issue has been fixed
