### ISSUE TITLE
Getitng issue with getFilterAttribute API

### ISSUE THREAD

**Issue by VikasTiwari-Webkul** [bagisto/headless-ecommerce#136]
We are getting Internal server error at getFilterAttribute API.

![Screenshot from 2024-01-31 15-43-32](https://github.com/bagisto/headless-ecommerce/assets/59952963/0fb14679-3080-463a-976b-9073afe05dcc)

**Comment by Anmol-Chauhan** [comment]
@VikasTiwari-Webkul use `key: "category_slug"
            value: "aszdfs"` filter

**Comment by Anmol-Chauhan** [comment]
Ignore

**Comment by NishantSharma12** [comment]
Fixed.

**Screenshot**

![Screenshot from 2024-03-13 13-12-37](https://github.com/bagisto/headless-ecommerce/assets/113347734/897f590a-118f-4212-839f-9900743fd102)
