### ISSUE TITLE
Requesting an API to retrieve CMS page data

### ISSUE THREAD

**Issue by VikasTiwari-Webkul** [bagisto/headless-ecommerce#137]
Requesting an API to retrieve CMS page data based on the page URL key.

**Comment by Anmol-Chauhan** [comment]
@VikasTiwari-Webkul use `Get All Cms Page List` API to get CMS Page Lisitng

**Comment by NishantSharma12** [comment]
As discussed with @Anmol-Chauhan use Get All Cms Page List API to get CMS Page Listing and the api is working.

**Screenshot**

![Screenshot from 2024-03-14 10-52-04](https://github.com/bagisto/headless-ecommerce/assets/113347734/4e0f64f1-7af0-4593-8fbc-0bc2c04859ec)
