### ISSUE TITLE
Method 'getCategoriesTree' does not exist on class

### ISSUE THREAD

**Issue by KyawNaingTun** [bagisto/headless-ecommerce#138]
I have been getting the following error response every time. How can I fix it? OR Why is it happening like that?
**Bagisto version: 2.0.0**

![GraphiQLerror](https://github.com/bagisto/headless-ecommerce/assets/6079250/a777addf-30d1-427f-8678-e5e3d19f49c4)

**Comment by 3likayed** [comment]
I have the same issue

**Comment by Anmol-Chauhan** [comment]
The issue has been fixed, Check now with the new installation of API

**Comment by NishantSharma12** [comment]
Fixed.

**Screenshot**

![Uploading Screenshot from 2024-03-14 10-56-54.png…]()
