### ISSUE TITLE
Customer is able to register account without domain email address.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#141]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Shop >> Customer Acount >>Register Customer

**Postman Screenshot**

![Screenshot from 2024-02-29 16-42-04](https://github.com/bagisto/headless-ecommerce/assets/113347734/1790d593-b7fd-4f54-9907-26b63f9c3450)

**Admin Screenshot**

![Screenshot from 2024-03-01 11-43-01](https://github.com/bagisto/headless-ecommerce/assets/113347734/28b9f124-1611-4377-9fb3-2c4a38bc8412)

**Web Screenshot**

![Screenshot from 2024-03-01 11-48-05](https://github.com/bagisto/headless-ecommerce/assets/113347734/08382094-00bb-4cbd-87b7-7884d3514e1c)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12 As the Bagisto functionality need to manage validation from the front-end
