### ISSUE TITLE
Customer is able to update account detail without domain email address

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#145]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Shop >> Customer Acount >>Update Account Detail

**Postman Screenshot**

![Screenshot from 2024-02-29 17-48-24](https://github.com/bagisto/headless-ecommerce/assets/113347734/744379d4-5be5-4e8d-9b99-fa93e27fcb90)

**Web Screenshot**

![Screenshot from 2024-03-01 12-29-59](https://github.com/bagisto/headless-ecommerce/assets/113347734/e60183c3-3413-4f1b-b118-33e25c3614a5)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12 Need to manage it from the front end

**Comment by NishantSharma12** [comment]
As @Anmol-Chauhan mentioned validation functionality will be manage from the Bagisto front-end not from the API end.
