### ISSUE TITLE
Able to social signup without domain email address. 

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#148]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Shop >> Customer Acount >> Social Signup

**Postman Screenshot**

![Screenshot from 2024-02-29 18-13-09](https://github.com/bagisto/headless-ecommerce/assets/113347734/83a29966-ca48-4874-a863-babf64ec4de6)

**Comment by Anmol-Chauhan** [comment]
Need to manage validation from frontend

**Comment by NishantSharma12** [comment]
As @Anmol-Chauhan  mentioned and discussed validation functionality will be manage from the Bagisto front-end not from the API end.
