### ISSUE TITLE
First and last name is saved for both create new and update address.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#149]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Shop >> Customer's Addresses  >>Create New Address

**Postman Screenshots**

![Screenshot from 2024-02-29 18-48-46](https://github.com/bagisto/headless-ecommerce/assets/113347734/d36f1f72-9378-4749-901e-7b637a199e8b)

![Screenshot from 2024-02-29 18-43-08](https://github.com/bagisto/headless-ecommerce/assets/113347734/dd4340da-9688-4aa3-9baf-6d0196f2da3b)

**API** - Shop >> Customer's Addresses  >> Update Address

**Postman Screenshots**

![Screenshot from 2024-02-29 19-03-20](https://github.com/bagisto/headless-ecommerce/assets/113347734/4cfc2603-616f-4952-9e73-84a84b273908)

![Screenshot from 2024-02-29 18-43-08](https://github.com/bagisto/headless-ecommerce/assets/113347734/d026fe63-20fc-4fbd-b220-061730377291)

**Web Screenshot**

![Screenshot from 2024-03-01 13-09-40](https://github.com/bagisto/headless-ecommerce/assets/113347734/9b444bfb-b3fb-4ecd-b2fd-3870e5fbcbb7)

**Comment by NishantSharma12** [comment]
@Anmol-Chauhan please check this issue for the v2.1.2.

**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Shop >> Customer's Addresses  >>Create New Address

**Postman Screenshots**

![Screenshot from 2024-03-13 12-04-03](https://github.com/bagisto/headless-ecommerce/assets/113347734/5e6a2c33-884e-47db-b81b-98661905fbb4)

![Screenshot from 2024-03-13 12-04-24](https://github.com/bagisto/headless-ecommerce/assets/113347734/67bfa418-b345-4f11-9c65-9495421b526c)

**API** - Shop >> Customer's Addresses  >> Update Address

**Postman Screenshots**

![Screenshot from 2024-03-13 12-04-45](https://github.com/bagisto/headless-ecommerce/assets/113347734/508ec58d-5e62-474d-baa3-7ce88b8bbbfd)

![Screenshot from 2024-03-13 12-05-00](https://github.com/bagisto/headless-ecommerce/assets/113347734/7f578e97-3a27-4568-826b-50e94e215721)

**Comment by nishant-webkul** [comment]
Fixed in v2.2.2

Bagisto - v2.2.2

Bagisto-headless - v2.2.2

API - Shop >> Customer's Addresses >>Create New Address

Postman Screenshots:

![Screenshot from 2024-10-04 12-53-55](https://github.com/user-attachments/assets/cee7ff48-6d2d-428b-8c75-8f43ad9656fe)

![Screenshot from 2024-10-04 12-54-31](https://github.com/user-attachments/assets/3aed595e-4ede-4f23-80c6-7e2230dde9c3)
