### ISSUE TITLE
Show status "null" in Get Order's Shipment List response

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#151]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Shop >> Customer's Orders >> Get Order's Shipment List

**Postman Screenshot**

![Screenshot from 2024-03-01 10-17-03](https://github.com/bagisto/headless-ecommerce/assets/113347734/c1a798b0-27e3-4156-9cec-48ca3a09511d)

**Comment by Anmol-Chauhan** [comment]
Null value is coming from the database if the status will update then the latest value will be returned
