### ISSUE TITLE
Show status "null" in Get Order's Shipment response.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#152]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Shop >> Customer's Orders >> Get Order's Shipment

**Postman Screenshot**

![Screenshot from 2024-03-01 11-14-06](https://github.com/bagisto/headless-ecommerce/assets/113347734/f4407c79-77fd-485b-8d76-ca50ea327481)

**Comment by Anmol-Chauhan** [comment]
https://github.com/bagisto/headless-ecommerce/issues/152

**Comment by NishantSharma12** [comment]
Show same status as "null" on database as well.

**Screenshot**

![Screenshot from 2024-03-13 17-45-44](https://github.com/bagisto/headless-ecommerce/assets/113347734/e84f253e-9cbb-4717-a490-b35c9df6ecfe)
