### ISSUE TITLE
Able to add new item in cart with "0" quantity.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#153]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Shop >> Cart >> Add New Item To Cart

**Postman Screenshot**

![Screenshot from 2024-03-06 09-33-18](https://github.com/bagisto/headless-ecommerce/assets/113347734/49ff5003-d850-4e84-a60d-57fd9a0e85b3)

**Web Screenshot**

![Screenshot from 2024-03-06 09-32-51](https://github.com/bagisto/headless-ecommerce/assets/113347734/6d9a3410-c89c-4c44-865a-7e48a81b03fe)

**Comment by Anmol-Chauhan** [comment]
For that case we managing internally and in that case min quantity 1 is added

**Comment by NishantSharma12** [comment]
As per @Anmol-Chauhan above comment.I'm closing this issue.
