### ISSUE TITLE
Improve success message when no product in cart page.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#158]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**Message** - "Warning: There is no product found."

**API** - Shop >> Cart >> Update Cart Items

**Postman Screenshot**

![Screenshot from 2024-03-06 09-45-17](https://github.com/bagisto/headless-ecommerce/assets/113347734/c9fc2ab0-2597-4b86-9abd-5f8f8e9ecb92)

**Comment by NishantSharma12** [comment]
As discussed with @Anmol-Chauhan this issue will fix in v2.1.2

**Comment by nishant-webkul** [comment]
Fixed in v2.2.2

Bagisto - v2.2.2

Bagisto-headless - v2.2.2

API - Shop >> Cart >> Update Cart Items

Postman Screenshot:

![Screenshot from 2024-10-04 12-56-53](https://github.com/user-attachments/assets/bda89cf3-fb16-4e13-ad0d-d8a626583673)
