### ISSUE TITLE
Getting "internal Server Error" in Get Categories Tree API.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#163]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Shop >> Common >> Get Categories Tree

**Postman Screenshot**

![Screenshot from 2024-03-06 16-34-45](https://github.com/bagisto/headless-ecommerce/assets/113347734/1fdc90c4-e5e7-44e8-aa90-0daa6ee5ff40)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12, No need for this API so removing this one

**Comment by NishantSharma12** [comment]
API Removed.

**Screenshot**

![Screenshot from 2024-03-13 12-40-05](https://github.com/bagisto/headless-ecommerce/assets/113347734/d7cd82cf-1ece-4829-8bcc-5e0dcefac027)
