### ISSUE TITLE
Getting "Internal Server Error" if send unavailable id. 

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#164]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Shop >> Common >> Send Notification

**Postman Screenshot**

![Screenshot from 2024-03-06 16-25-34](https://github.com/bagisto/headless-ecommerce/assets/113347734/73a54c87-7131-4f3f-90c8-42637a9d1a60)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12, We will fix such types of issues and all validations issues in the next version

**Comment by NishantSharma12** [comment]
As per discussion with @Anmol-Chauhan will work on these issues in v2.1.2
