### ISSUE TITLE
Email validation required if admin try to login without domain with email address.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#165]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Session Request >> User Login

**Postman Screenshot**

![Screenshot from 2024-03-06 17-24-57](https://github.com/bagisto/headless-ecommerce/assets/113347734/113327d2-6222-4137-a799-aee14a8cd8de)

**Admin Screenshot**

![Screenshot from 2024-03-06 17-24-48](https://github.com/bagisto/headless-ecommerce/assets/113347734/1d8777af-7761-494d-9124-7a2b566dcd10)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12 need to manage this from the frontend

**Comment by NishantSharma12** [comment]
As @Anmol-Chauhan  mentioned validation functionality will be manage from the Bagisto front-end not from the API end.
