### ISSUE TITLE
With unavailable channel number admin is able to create CMS page.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#167]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Cms >> Create Cms Page

**Postman Screenshot**

![Screenshot from 2024-03-07 09-52-40](https://github.com/bagisto/headless-ecommerce/assets/113347734/3d90ce52-5827-4e9a-80df-4b6d8ffbc297)

**Web Screenshot**

![Screenshot from 2024-03-07 09-53-03](https://github.com/bagisto/headless-ecommerce/assets/113347734/23ef1ebc-1111-418a-a149-3e336094128a)
-4d55-9828-69f181c16a99)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12 , We will fix such types of issues and all validations issues in the next version

**Comment by NishantSharma12** [comment]
As discussed with @Anmol-Chauhan will fix this issue in v2.1.2
