### ISSUE TITLE
CMS page content is not updating.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#168]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Cms >> Update Cms Page

**Postman Screenshot**

![Screenshot from 2024-03-07 10-15-37](https://github.com/bagisto/headless-ecommerce/assets/113347734/63520599-cd0f-4a6a-8eb2-71e1e18c05a7)

**Web Screenshot**

![Screenshot from 2024-03-07 10-15-48](https://github.com/bagisto/headless-ecommerce/assets/113347734/30f8f235-096c-47c5-8290-61bc3f6f47c0)

![Screenshot from 2024-03-07 10-16-01](https://github.com/bagisto/headless-ecommerce/assets/113347734/f944c82a-d0cb-4a7f-b87b-f4f628385642)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12, Check you are updating this for another locale and check the changes in En locale

**Comment by NishantSharma12** [comment]
Fixed.

**Screenshot**

![Screenshot from 2024-03-19 10-21-19](https://github.com/bagisto/headless-ecommerce/assets/113347734/08e67c78-639f-479d-a73b-f6c0764889c0)

![Screenshot from 2024-03-19 10-21-05](https://github.com/bagisto/headless-ecommerce/assets/113347734/202bd778-1b5b-4874-802e-473072aacaec)

![Screenshot from 2024-03-19 10-21-12](https://github.com/bagisto/headless-ecommerce/assets/113347734/adf2fd15-1efc-43e4-9c7d-bebf38c8002b)
