### ISSUE TITLE
With unavailable customer group admin is able to create and update catalog rule.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#171]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Marketing >> Promotions >> Catalog Rule >> Create Catalog Rule

**Postman Screenshot**

![Screenshot from 2024-03-07 10-48-35](https://github.com/bagisto/headless-ecommerce/assets/113347734/80fbc951-64db-4dcf-b775-444c89b5f287)

**Web Screenshot**

![Screenshot from 2024-03-07 10-48-45](https://github.com/bagisto/headless-ecommerce/assets/113347734/6294ddcf-8e11-4d00-87e0-aa0b6fcb63e5)

**API** - Admin >> Marketing >> Promotions >> Catalog Rule >> Update Catalog Rule

**Postman Screenshot**

![Screenshot from 2024-03-07 11-17-41](https://github.com/bagisto/headless-ecommerce/assets/113347734/2dcca5af-9704-484a-9217-89ba2181c110)

**Web Screenshot**

![Screenshot from 2024-03-07 11-17-30](https://github.com/bagisto/headless-ecommerce/assets/113347734/f378a5ff-e8ec-4c0b-b13f-f66ab71efa1e)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12, We will fix such types of issues and all validations issues in the next version

**Comment by NishantSharma12** [comment]
As discussed with @Anmol-Chauhan  will fix this issue in v2.1.2
