### ISSUE TITLE
With unavailable customer group admin is able to create and update cart rule.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#173]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Marketing >> Promotions >> Cart Rule >> Create Cart Rule

**Postman Screenshot**

![Screenshot from 2024-03-07 12-08-01](https://github.com/bagisto/headless-ecommerce/assets/113347734/cb76f0a0-b8b6-4325-9abd-e79d06ec8986)

**Web Screenshot**

![Screenshot from 2024-03-07 12-07-14](https://github.com/bagisto/headless-ecommerce/assets/113347734/b23f0fbb-eb35-4075-aaeb-5a45fdf3bafb)

**API** - Admin >> Marketing >> Promotions >> Cart Rule >> Update Cart Rule

**Postman Screenshot**

![Screenshot from 2024-03-07 12-14-58](https://github.com/bagisto/headless-ecommerce/assets/113347734/8762db3a-bb5d-4edc-a700-60f0fc665793)

**Web Screenshot**

![Screenshot from 2024-03-07 12-18-24](https://github.com/bagisto/headless-ecommerce/assets/113347734/fe970827-d07a-475b-91d5-4548ba14a71c)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12, We will fix such types of issues and all validations issues in the next version

**Comment by NishantSharma12** [comment]
As discussed with @Anmol-Chauhan will fix this issue in v2.1.2
