### ISSUE TITLE
With unavailable channel number admin is able to create and update cart rule.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#174]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Marketing >> Promotions >> Catalog Rule >> Create Cart Rule

**Postman Screenshot**

![Screenshot from 2024-03-07 12-06-17](https://github.com/bagisto/headless-ecommerce/assets/113347734/84fa04bb-8f30-4fe5-9160-50624938da44)

**Web Screenshot**

![Screenshot from 2024-03-07 12-06-08](https://github.com/bagisto/headless-ecommerce/assets/113347734/d2fc4280-11ad-42e8-aff8-7650bc1b6bb4)

**API** - Admin >> Marketing >> Promotions >> Catalog Rule >> Update Cart Rule

**Postman Screenshot**

![Screenshot from 2024-03-07 12-14-27](https://github.com/bagisto/headless-ecommerce/assets/113347734/f7aa9d11-0528-4035-9603-ee4ca4d6c5a7)

**Web Screenshot**

![Screenshot from 2024-03-07 12-14-35](https://github.com/bagisto/headless-ecommerce/assets/113347734/4b6698d1-0483-4e9f-a1e1-20a2412c089b)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12, We will fix such types of issues and all validations issues in the next version

**Comment by NishantSharma12** [comment]
As discussed with @Anmol-Chauhan  will fix this issue in v2.1.2
