### ISSUE TITLE
If email template status is "inactive", then admin should not able to create or update the campaign with same "emailTemplateId".

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#180]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Marketing >> Communications >> Campaign >> Create Campaign

**Postman Screenshot**

![Screenshot from 2024-03-07 13-46-20](https://github.com/bagisto/headless-ecommerce/assets/113347734/d18978c0-41ae-4c39-8560-1c4bde262c04)

**API** - Admin >> Marketing >> Communications >> Campaign >> Update Campaign

**Postman Screenshot**

![Screenshot from 2024-03-07 13-49-31](https://github.com/bagisto/headless-ecommerce/assets/113347734/dcfc31e3-025c-4e01-8899-bb759c26a385)

**Web Screenshot**

![Screenshot from 2024-03-07 13-46-44](https://github.com/bagisto/headless-ecommerce/assets/113347734/4be05a9a-4bf1-4e8c-91b5-93617f3f6beb)

![Screenshot from 2024-03-07 13-46-58](https://github.com/bagisto/headless-ecommerce/assets/113347734/d8f68547-f4d8-4fb8-8be1-f582ac50e32c)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12, We will fix such types of issues and all validations issues in the next version

**Comment by NishantSharma12** [comment]
As discussed with @Anmol-Chauhan will fix this issue in v2.1.2
