### ISSUE TITLE
Need email validation for the email parameter.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#182]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Marketing >> Communications >> Subscribers >> Get Subscriber Details

**Postman Screenshot**

![Screenshot from 2024-03-07 13-57-40](https://github.com/bagisto/headless-ecommerce/assets/113347734/2c77bcb5-e9c4-4ae7-aeea-799459985716)

**API** - Admin >> Marketing >> Communications >> Subscribers >> Remove Subscriber

**Postman Screenshot**

![Screenshot from 2024-03-07 14-00-17](https://github.com/bagisto/headless-ecommerce/assets/113347734/95eb3dd6-fd2d-48d3-8ed8-2ec974237d37)

**Comment by NishantSharma12** [comment]
Will fix this issue in v2.1.2

**Comment by nishant-webkul** [comment]
Fixed in v2.2.2

Bagisto - v2.2.2

Bagisto-headless - v2.2.2

API - Admin >> Marketing >> Communications >> Subscribers >> Get Subscriber Details

Postman Screenshot:

![Screenshot from 2024-10-04 12-59-37](https://github.com/user-attachments/assets/c4bb046c-de46-4ded-a813-ed5116d60322)

![Screenshot from 2024-10-04 12-59-16](https://github.com/user-attachments/assets/586180f1-fb2a-420f-82fb-442aab3016a6)
