### ISSUE TITLE
Image is not uploaded while create new locale.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#186]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Locale >> Create

**Postman Screenshot**

![Screenshot from 2024-03-07 16-15-05](https://github.com/bagisto/headless-ecommerce/assets/113347734/e33645e4-aba5-4a26-96ac-1f1f3a6b7484)

**Web Screenshot**

![Screenshot from 2024-03-07 16-15-35](https://github.com/bagisto/headless-ecommerce/assets/113347734/0a6461b3-001b-4048-8637-b44cc7a32253)

**API** - Admin >> Settings >> Locale >> Update

**Postman Screenshot**

![Screenshot from 2024-03-07 16-29-55](https://github.com/bagisto/headless-ecommerce/assets/113347734/cb7dfae6-8e9e-4680-b90d-5e900e274407)

**Web Screenshot**

![Screenshot from 2024-03-07 16-30-20](https://github.com/bagisto/headless-ecommerce/assets/113347734/00e67623-a72c-4399-b316-79875dfa1883)

**Comment by NishantSharma12** [comment]
@Anmol-Chauhan Please recheck this issue. After image upload, the uploaded image is not visible at admin end after open the image link.

**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Locale >> Create

**Postman Screenshot**

![Screenshot from 2024-03-13 18-48-38](https://github.com/bagisto/headless-ecommerce/assets/113347734/1089d215-68c1-4f15-adae-b859265ccc58)

**Web Screenshot**

![Screenshot from 2024-03-13 18-48-58](https://github.com/bagisto/headless-ecommerce/assets/113347734/ac221aae-4aa0-41aa-a470-f9cbaa7093dd)

![Screenshot from 2024-03-13 18-49-20](https://github.com/bagisto/headless-ecommerce/assets/113347734/996247fd-883a-4ac0-a386-2ea2d740f8f5)

**API** - Admin >> Settings >> Locale >> Update

**Postman Screenshot**

![Screenshot from 2024-03-13 18-51-46](https://github.com/bagisto/headless-ecommerce/assets/113347734/28d1a3be-b204-4115-836f-79f4de532fcb)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12, You need to update the image path while creating or updating locale

**Comment by NishantSharma12** [comment]
Fixed.

**Screenshot**

![Screenshot from 2024-03-21 16-58-09](https://github.com/bagisto/headless-ecommerce/assets/113347734/3c5eb8c4-b53e-4b90-9d85-ccb634570559)

![Screenshot from 2024-03-21 16-58-40](https://github.com/bagisto/headless-ecommerce/assets/113347734/d2f9d224-d606-4d58-a0ed-9402bfa3c80c)

![Screenshot from 2024-03-21 16-59-49](https://github.com/bagisto/headless-ecommerce/assets/113347734/b7a2c2be-74e4-40a4-bb5f-d02f2290d825)
