### ISSUE TITLE
Decimal parameter is not available in the API Request.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#187]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Currencies >> Create

**Postman Screenshot**

![Screenshot from 2024-03-07 16-55-05](https://github.com/bagisto/headless-ecommerce/assets/113347734/417e6708-3a2e-450e-8daa-dc893a23ad0d)

**API** - Admin >> Settings >> Currencies >> Update

**Postman Screenshot**

![Screenshot from 2024-03-07 16-55-14](https://github.com/bagisto/headless-ecommerce/assets/113347734/ef769a87-1d79-4c70-b452-84a0ccaaa598)

**Web Screenshot**

![Screenshot from 2024-03-07 16-49-50](https://github.com/bagisto/headless-ecommerce/assets/113347734/a43c8681-3af1-463d-b226-49c29cc3bd0a)

**Comment by NishantSharma12** [comment]
@Anmol-Chauhan Please add the Decimal parameter in the update api and show the decimal value in the response also.

**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Currencies >> Create

**Postman Screenshot**

![Screenshot from 2024-03-13 13-38-40](https://github.com/bagisto/headless-ecommerce/assets/113347734/b6183022-646a-43bd-aa5a-de812ac6b3c4)

**API** - Admin >> Settings >> Currencies >> Update

**Postman Screenshot**

![Screenshot from 2024-03-13 13-38-54](https://github.com/bagisto/headless-ecommerce/assets/113347734/d63dc0e5-6a45-4e68-9fc4-d86f9255a888)

**Comment by NishantSharma12** [comment]
@Anmol-Chauhan please show the decimal value in the response also.

**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Currencies >> Create

**Postman Screenshot**

![Screenshot from 2024-03-19 10-32-37](https://github.com/bagisto/headless-ecommerce/assets/113347734/f214e121-a73f-4d26-838e-471b03bfb2ef)

**API** - Admin >> Settings >> Currencies >> Update

**Postman Screenshot**

![Screenshot from 2024-03-19 10-33-22](https://github.com/bagisto/headless-ecommerce/assets/113347734/5a8b95a6-9799-4b5f-867f-162911772c6c)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12, in currencies query their is all fields available you can add or remove according to need

**Comment by NishantSharma12** [comment]
As discussed with @Anmol-Chauhan user can add or remove the parameters as per need in the api.
