### ISSUE TITLE
Need validation for the invalid countries.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#197]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Inventory Sources >> Create

**Postman Screenshot**

![Screenshot from 2024-03-08 11-07-55](https://github.com/bagisto/headless-ecommerce/assets/113347734/479e1ccb-b44f-4c01-addb-cb0fa98e402f)

**API** - Admin >> Settings >> Inventory Sources >> Update

**Postman Screenshot**

![Screenshot from 2024-03-08 11-11-17](https://github.com/bagisto/headless-ecommerce/assets/113347734/9ff0dcd6-2b59-4816-8791-12497a1d5543)

**Web Screenshot**

![Screenshot from 2024-03-08 11-11-56](https://github.com/bagisto/headless-ecommerce/assets/113347734/d94644e9-aa57-437b-9692-40a56df4c62f)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12 Pass the country which you are getting in Countries API response

**Comment by NishantSharma12** [comment]
ok
