### ISSUE TITLE
Getting "Internal Server Error" in response if request for create or update user more than 1 time without email parameter.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#206]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Users >> Create User

**Postman Screenshot**

![Screenshot from 2024-03-08 16-48-13](https://github.com/bagisto/headless-ecommerce/assets/113347734/98b87b5d-d444-40b5-a955-2566e1e93708)

**API** - Admin >> Settings >> Users >> Update User

**Postman Screenshot**

![Screenshot from 2024-03-08 16-48-40](https://github.com/bagisto/headless-ecommerce/assets/113347734/648436ed-4aca-4a8b-8a06-cea4c510bae0)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12, I am not facing any such issue

**Comment by NishantSharma12** [comment]
Fixed.

**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Users >> Create User

**Postman Screenshot**

![Screenshot from 2024-03-13 16-00-52](https://github.com/bagisto/headless-ecommerce/assets/113347734/b44688db-043b-4f21-ac78-d57e501c0749)

**API** - Admin >> Settings >> Users >> Update User

**Postman Screenshot**

![Screenshot from 2024-03-13 16-01-49](https://github.com/bagisto/headless-ecommerce/assets/113347734/1a5718af-1a9e-4d26-8805-807589127b65)
