### ISSUE TITLE
Able to create user without password validation.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#208]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Users >> Create User

**Postman Screenshot**

![Screenshot from 2024-03-08 17-00-26](https://github.com/bagisto/headless-ecommerce/assets/113347734/bbe482a5-73e0-4fee-bf3b-c43c1688f178)

**Web Screenshot**

![Screenshot from 2024-03-08 17-07-57](https://github.com/bagisto/headless-ecommerce/assets/113347734/2c54b6b9-6b84-496e-9f43-0ecdb2d99a80)

**Comment by NishantSharma12** [comment]
@Anmol-Chauhan please recheck this issue.

**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Users >> Create User

**Postman Screenshot**

![Screenshot from 2024-03-13 17-55-04](https://github.com/bagisto/headless-ecommerce/assets/113347734/89e10efb-d956-4780-9367-fa04493f591c)

**Comment by Anmol-Chauhan** [comment]
https://github.com/bagisto/headless-ecommerce/issues/207

**Comment by nishant-webkul** [comment]
Fixed in v2.2.2

Bagisto - v2.2.2

Bagisto-headless - v2.2.2

API - Admin >> Settings >> Users >> Create User

Postman Screenshot:

![Screenshot from 2024-10-04 13-11-07](https://github.com/user-attachments/assets/54a75c0d-52f4-417e-a214-ba96a4b77c4d)
