### ISSUE TITLE
Getting "Internal Server Error" in response if request for update user with wrong password validation parameters.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#210]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Users >> Update User

**Postman Screenshot**

![Screenshot from 2024-03-08 17-08-55](https://github.com/bagisto/headless-ecommerce/assets/113347734/d6e5f606-7374-4762-b2a8-bd9f6a558ef7)

**Comment by NishantSharma12** [comment]
@Anmol-Chauhan please check this issue. Now able to update user details with invalid password.

**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Users >> Update User

**Postman Screenshot**

![Screenshot from 2024-03-13 16-13-14](https://github.com/bagisto/headless-ecommerce/assets/113347734/d28b3217-fb87-4464-8623-ac63007c900d)

**Web Screenshot**

![Screenshot from 2024-03-13 16-13-01](https://github.com/bagisto/headless-ecommerce/assets/113347734/d68586da-24c7-4cb2-a7d2-5e44dcb19ab9)

**Comment by Anmol-Chauhan** [comment]
https://github.com/bagisto/headless-ecommerce/issues/207

**Comment by NishantSharma12** [comment]
Fixed.

**Screenshot**

![Screenshot from 2024-03-21 17-10-13](https://github.com/bagisto/headless-ecommerce/assets/113347734/0136c2a7-bc54-45e9-a280-5c5650c4e213)
