### ISSUE TITLE
 composer require bagisto/graphql-api dev-main failed with  Bagisto v2.1.2

### ISSUE THREAD

**Issue by liuchiente** [bagisto/headless-ecommerce#211]
Declaration of Webkul\GraphQLAPI\Models\CatalogRule\CatalogRule::catalog_rule_products() must be compatible with Webkul\CatalogRule\Models\CatalogRule::catalog_rule_products(): Illuminate\Database\Eloquent\Relations\HasMany

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12, check this for v2.0.0 and update accordingly

**Comment by NishantSharma12** [comment]
@liuchiente Currently it's compatible with v2.0.0
We are working on some issues and after fixing the issues we will update this for v2.1.2

Please check the below screenshot for compatibility with v2.0.0

![Screenshot from 2024-03-11 13-22-00](https://github.com/bagisto/headless-ecommerce/assets/113347734/87c58276-9da4-43d0-b5b2-1ea1470301b1)
