### ISSUE TITLE
Able to create or update the user role with unavailable permissionType parameter.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#213]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Settings >> Roles >> Create

**Postman Screenshot**

![Screenshot from 2024-03-11 11-42-56](https://github.com/bagisto/headless-ecommerce/assets/113347734/dd82ede4-c753-43bc-88cc-f600669abe06)

**API** - Admin >> Settings >> Roles >> Update

**Postman Screenshot**

![Screenshot from 2024-03-11 11-43-13](https://github.com/bagisto/headless-ecommerce/assets/113347734/b3c08ffa-3bc9-4f59-8f7f-4a5e1d14d494)

**Web Screenshot**

![Screenshot from 2024-03-11 11-43-22](https://github.com/bagisto/headless-ecommerce/assets/113347734/43492fd7-b4bc-4f16-8901-e64ea4614237)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12, We will fix such types of issues and all validations issues in the next version

**Comment by NishantSharma12** [comment]
https://github.com/bagisto/headless-ecommerce/issues/202
