### ISSUE TITLE
Getting status "null" in response for orders shipment api.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#217]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Sales >> Orders >> Order's Shipments

**Postman Screenshot**

![Screenshot from 2024-03-11 14-51-24](https://github.com/bagisto/headless-ecommerce/assets/113347734/00e623e6-61ce-498e-b38a-d11e55089b9e)

**API** - Admin >> Sales >> Orders >> Order's Shipment

**Postman Screenshot**

![Screenshot from 2024-03-11 14-54-23](https://github.com/bagisto/headless-ecommerce/assets/113347734/07a07164-9863-446e-97c9-5a61ab67e91f)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12 Getting null because there is no value in DB for status

**Comment by NishantSharma12** [comment]
As @Anmol-Chauhan mentioned on above this value comes from the DB.

**Screenshot**

![312452093-73667fcf-a7fd-4afb-b662-428034f5a7a5](https://github.com/bagisto/headless-ecommerce/assets/113347734/2f4c4f02-8252-40c1-9ba4-7df62844041a)

![312452304-e84f253e-9cbb-4717-a490-b35c9df6ecfe](https://github.com/bagisto/headless-ecommerce/assets/113347734/9d16f31d-09d5-4043-bcc0-e5f6f677abe7)
