### ISSUE TITLE
Getting "Internal Server Error" when trying to update the grouped product.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#227]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Catalog >> Products >> Update Grouped Product

**Postman Screenshot**

![Screenshot from 2024-03-12 12-04-30](https://github.com/bagisto/headless-ecommerce/assets/113347734/de1775e9-3949-4290-b04b-46252f760094)

**Web Screenshot**

![Screenshot from 2024-03-12 12-04-37](https://github.com/bagisto/headless-ecommerce/assets/113347734/ebe67e54-e57b-4760-b854-29728fbd6416)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12 you are passing invalid product Id

**Comment by NishantSharma12** [comment]
As discussed with @Anmol-Chauhan this issue will fix in v2.1.2
