### ISSUE TITLE
Getting error message when trying to update the bundle product.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#228]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Catalog >> Products >> Update Bundle Product

**Postman Screenshot**

![Screenshot from 2024-03-12 12-44-14](https://github.com/bagisto/headless-ecommerce/assets/113347734/66412ea8-3129-4fef-9b90-c3d8c573db2c)

**Web Screenshot**

![Screenshot from 2024-03-12 12-46-19](https://github.com/bagisto/headless-ecommerce/assets/113347734/44c26837-85d2-4128-8041-fe008508c97a)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12 You are passing invalid options product id

**Comment by NishantSharma12** [comment]
Fixed.

**Screenshot**

![Screenshot from 2024-03-19 12-05-25](https://github.com/bagisto/headless-ecommerce/assets/113347734/5b1e49dc-1743-4e58-ac80-3432489370de)
