### ISSUE TITLE
Getting "Internal Server Error" when trying to update the configurable product.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/headless-ecommerce#230]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Catalog >> Products >> Update Configurable Product

**Postman Screenshot**

![Screenshot from 2024-03-12 13-40-34](https://github.com/bagisto/headless-ecommerce/assets/113347734/811c7187-9d12-423d-a9e0-725888b1c5cc)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12 You are passing invalid varients id

**Comment by NishantSharma12** [comment]
Fixed.

**Screenshot**

![Screenshot from 2024-03-19 11-51-17](https://github.com/bagisto/headless-ecommerce/assets/113347734/2b63caf9-d63a-426a-8bfd-eb29a76517f3)
