### ISSUE TITLE
Getting "Internal Server Error" when create or update category without position parameter.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#236]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Catalog >> Categories >> Create New Category

**Postman Screenshot**

![Screenshot from 2024-03-12 15-55-29](https://github.com/bagisto/headless-ecommerce/assets/113347734/c74a1599-63ea-453e-986b-391f475c65d2)

**API** - Admin >> Catalog >> Categories >> Update Category Details

**Postman Screenshot**

![Screenshot from 2024-03-12 16-10-44](https://github.com/bagisto/headless-ecommerce/assets/113347734/7f260fd2-0b42-4cc8-9743-b5439d5575ad)

**Comment by nishant-webkul** [comment]
@mayank-webkul please recheck this issue for the update API.

Bagisto - v2.2.2

Bagisto-headless - v2.2.2

API - Admin >> Catalog >> Categories >> Update Category

Postman Screenshot:

![Screenshot from 2024-10-04 13-39-16](https://github.com/user-attachments/assets/cf7ffcc5-79c1-4056-996e-e49438f64076)

**Comment by mayank-webkul** [comment]
@nishant-webkul please check my previous comment https://github.com/bagisto/headless-ecommerce/issues/236#issuecomment-2368207103

**Comment by nishant-webkul** [comment]
Fixed.

Bagisto - v2.2.2

Bagisto-headless - v2.2.2

API - Admin >> Catalog >> Categories >> Update Category

Postman Screenshot:

![Screenshot from 2024-10-22 16-01-04](https://github.com/user-attachments/assets/5191a196-9692-44a3-b729-3da5ce7df8ae)

![Screenshot from 2024-10-22 16-01-11](https://github.com/user-attachments/assets/09747f6a-78e2-49e9-b3fa-8a2283019944)
