### ISSUE TITLE
First and last name, gender and email should not pass empty string while request create or update address.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#240]
**Bagisto** - v2.0.0

**Bagisto-headless** - v2.0.0

**API** - Admin >> Customers >> Customer's Addresses >> Create Customer's Address

**Postman Screenshot**

![Screenshot from 2024-03-12 18-16-08](https://github.com/bagisto/headless-ecommerce/assets/113347734/aa618212-f215-457e-bcc9-05fc1a712785)

![Screenshot from 2024-03-12 18-16-22](https://github.com/bagisto/headless-ecommerce/assets/113347734/5df297d7-ccc9-4445-b6b3-a36ec2abbdb2)

![Screenshot from 2024-03-12 18-16-41](https://github.com/bagisto/headless-ecommerce/assets/113347734/b720c33d-7f5b-417e-b84a-a6d1526cb432)

![Screenshot from 2024-03-12 18-16-57](https://github.com/bagisto/headless-ecommerce/assets/113347734/8ea9f795-79f4-4616-8285-51c6738bf01b)

**API** - Admin >> Customers >> Customer's Addresses >> Update Customer's Address

**Postman Screenshot**

![Screenshot from 2024-03-12 18-19-11](https://github.com/bagisto/headless-ecommerce/assets/113347734/48915ec5-3f23-4607-a1ea-529f40cd99db)

![Screenshot from 2024-03-12 18-19-40](https://github.com/bagisto/headless-ecommerce/assets/113347734/477bf71c-33ba-4db0-908d-04588adf77e6)

![Screenshot from 2024-03-12 18-20-08](https://github.com/bagisto/headless-ecommerce/assets/113347734/f6b60726-82e2-44d0-8e75-e2fa0c5acf3f)

![Screenshot from 2024-03-12 18-20-27](https://github.com/bagisto/headless-ecommerce/assets/113347734/e1e79b1b-529a-49de-8307-630158f7725a)

**Web Screenshot**

![Screenshot from 2024-03-12 18-18-35](https://github.com/bagisto/headless-ecommerce/assets/113347734/af36f8e3-9652-4de3-93ef-1f4abdfecad2)

**Comment by Anmol-Chauhan** [comment]
@NishantSharma12 It's already required field, need to add validation for empty string, will fix in next release

**Comment by nishant-webkul** [comment]
Fixed in v2.2.2

Bagisto - v2.0.0

Bagisto-headless - v2.0.0

API - Admin >> Customers >> Customer's Addresses >> Create Customer's Address

Postman Screenshot:

![Screenshot from 2024-10-04 13-46-47](https://github.com/user-attachments/assets/e7e1bf59-a5ea-4a0f-bd26-7409a9410efd)

![Screenshot from 2024-10-04 13-47-10](https://github.com/user-attachments/assets/d314697c-21d6-4a2b-99d4-e4bd716c05c4)
