### ISSUE TITLE
When will the Bajitsu 2.1.2 version be released?

### ISSUE THREAD

**Issue by imanbahmani** [bagisto/headless-ecommerce#247]
I have version 2.1.2 and I'm having trouble installing it through Composer
I wanted to know when a version compatible with this version will be released?

**Comment by imanbahmani** [comment]
please help me about this

**Comment by AHMED-GAMAL-AG** [comment]
i have the same problem @vivek-webkul ? 

installing using composer i get 

```
Symfony\Component\ErrorHandler\Error\FatalError

  Declaration of Webkul\GraphQLAPI\Models\CatalogRule\CatalogRule::catalog_rule_products() must be compatible with Webkul\CatalogRule\Models\CatalogRule::catalog_rule_products(): Illuminate\Database\Eloquent\Relations\HasMany

  at vendor\bagisto\graphql-api\src\Models\CatalogRule\CatalogRule.php:14
     10▕ {
     11▕     /**
     12▕      * Get the Catalog rule Product that owns the catalog rule.
     13▕      */
  ➜  14▕     public function catalog_rule_products()
     15▕     {
     16▕         return $this->hasMany(CatalogRuleProductProxy::modelClass());
     17▕     }
     18▕


   Whoops\Exception\ErrorException

  Declaration of Webkul\GraphQLAPI\Models\CatalogRule\CatalogRule::catalog_rule_products() must be compatible with Webkul\CatalogRule\Models\CatalogRule::catalog_rule_products(): Illuminate\Database\Eloquent\Relations\HasMany

  at vendor\bagisto\graphql-api\src\Models\CatalogRule\CatalogRule.php:14
     10▕ {
     11▕     /**
     12▕      * Get the Catalog rule Product that owns the catalog rule.
     13▕      */
  ➜  14▕     public function catalog_rule_products()
     15▕     {
     16▕         return $this->hasMany(CatalogRuleProductProxy::modelClass());
     17▕     }
     18▕

  1   vendor\filp\whoops\src\Whoops\Run.php:510
      Whoops\Run::handleError("Declaration of Webkul\GraphQLAPI\Models\CatalogRule\CatalogRule::catalog_rule_products() must be compatible with Webkul\CatalogRule\Models\CatalogRule::catalog_rule_products(): Illuminate\Database\Eloquent\Relations\HasMany", "C:\Users\ahmed\Herd\bagisto\vendor\bagisto\graphql-api\src\Models\CatalogRule\CatalogRule.php")

  2   [internal]:0
      Whoops\Run::handleShutdown()

PHP Fatal error:  Declaration of Webkul\GraphQLAPI\Models\CatalogRule\CatalogRule::catalog_rule_products() must be compatible with Webkul\CatalogRule\Models\CatalogRule::catalog_rule_products(): Illuminate\Database\Eloquent\Relations\HasMany in C:\Users\ahmed\Herd\bagisto\vendor\bagisto\graphql-api\src\Models\CatalogRule\CatalogRule.php on line 14
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
```

**Comment by Anmol-Chauhan** [comment]
@AHMED-GAMAL-AG,  I have checked and there is no such issue if you use Bagisto v2.0.0 and GraphQL v2.0.0, all is working fine. APIs are not compatible with the latest version of bagisto, The Team is working on it and will provide the updated APIs soon.

![Screenshot from 2024-05-08 11-21-15](https://github.com/bagisto/headless-ecommerce/assets/79086253/d2cd08ab-c00d-43a5-b2b5-324b42caf2d5)
![Screenshot from 2024-05-08 11-20-41](https://github.com/bagisto/headless-ecommerce/assets/79086253/829c7bde-aaf6-4023-9791-5c581fbae40e)
![Screenshot from 2024-05-08 11-20-22](https://github.com/bagisto/headless-ecommerce/assets/79086253/e1026e7d-e9ff-43d1-aa2d-ba631ef4eff6)

**Comment by Anmol-Chauhan** [comment]
@imanbahmani, The Team is working on it and will provide the updated APIs soon.

**Comment by imanbahmani** [comment]
> @imanbahmani, The Team is working on it and will provide the updated APIs soon.

It will be fully updated in about two weeks?

**Comment by Anmol-Chauhan** [comment]
@imanbahmani, In two weeks, we will update the front end completely.

**Comment by imanbahmani** [comment]
When will this version be released?

**Comment by imanbahmani** [comment]
When will this version 2.1.2 be released?

**Comment by mayank-webkul** [comment]
@imanbahmani We have updated the API for Bagisto v2.2.2, so there will be no release for v2.1.2. You can upgrade directly to v2.2.2, which is fully compatible with the latest version of Bagisto i.e. v2.2.2.
