### ISSUE TITLE
Bagisto 2 is not compatible with bagisto-graphql latest version

### ISSUE THREAD

**Issue by BrainClickAdsTeam** [bagisto/headless-ecommerce#250]
Hello everyone,

I am trying to install bagisto graphql admin api to existing bagisto 2 project, I have followed the docs here: https://devdocs.bagisto.com/1.x/graphql-admin-api/installation.html

And the graphql package is installed successfully with no issues, but when i try to send a login request as in the docs here:
https://devdocs.bagisto.com/1.x/graphql-admin-api/getting-started-with-the-api.html#introduction

Then i am getting this error:
Failed to find class Webkul\\CMS\\Models\\CmsPage in namespaces [App, Webkul\\GraphQLAPI\\Models] for directive @paginate.

Anyone has a solution for this issue?

Thanks.

**Comment by Anmol-Chauhan** [comment]
@BrainClickAdsTeam,
Hello,
We are upgrading the GraphQL API with the latest version of Bagisto. It will take some time, We will update you once it is compatible

**Comment by Anmol-Chauhan** [comment]
Hi @BrainClickAdsTeam, I have checked and there is no such issue if you use Bagisto v2.0.0 and GraphQL v2.0.0, all is working fine. APIs are not compatible with the latest version of bagisto, The 
![Screenshot from 2024-05-08 11-21-15](https://github.com/bagisto/headless-ecommerce/assets/79086253/d1240ebb-bf89-4033-b03c-b4069b2107af)
![Screenshot from 2024-05-08 11-20-41](https://github.com/bagisto/headless-ecommerce/assets/79086253/8716d854-f503-49e2-82f3-40586efaae53)
![Screenshot from 2024-05-08 11-20-22](https://github.com/bagisto/headless-ecommerce/assets/79086253/11d71c04-6316-4020-92c6-dbdaf191d42b)
Team is working on it and will provide the updated APIs soon.

**Comment by BrainClickAdsTeam** [comment]
I am using bagisto v2.0.0, but i think the issue is in the graphql installation, can please provide me with the installation guide about installing graphql admin apis for bagisto, because event the login request is not working for me

**Comment by BrainClickAdsTeam** [comment]
should i follow this doc? https://devdocs.bagisto.com/1.x/graphql-admin-api/installation.html

**Comment by BrainClickAdsTeam** [comment]
I have installed the rest-api previously in the project, might that be the issue??

**Comment by Anmol-Chauhan** [comment]
@BrainClickAdsTeam, Please follow the guide link:- https://github.com/bagisto/headless-ecommerce

**Comment by BrainClickAdsTeam** [comment]
I have followed the guide many times and still facing same issue, can i ask if the graphql play ground is working for you? can perform the same request with no issues from graphql play ground?

**Comment by BrainClickAdsTeam** [comment]
I have followed these steps exactly and still facing the same error:

1.  downloaded the bagisto v2.1.2 as zip file from main bagisto website
2. run composer install
3. connect bagisto to existing database
4. now bagisto front end and dashboard are working fine
5. after that i have visited this url: https://github.com/bagisto/headless-ecommerce
6. and installed the package
7. then i have added the graphql servive provider one time in the beginning of the modules array and once in the end of the modules array
8. then i have added the middleware to the middlewares array in the kernel file
9. after that i have updated the auth.php file in the config as requested, but i have noticed something
![Screenshot 2024-05-09 163831](https://github.com/bagisto/headless-ecommerce/assets/155820858/2043cab0-0328-45f5-8832-f3392e744dc4)


![Screenshot 2024-05-09 164101](https://github.com/bagisto/headless-ecommerce/assets/155820858/73f11fdf-caeb-4a1e-8a6b-e5566202c4df)

10. After that i have executed the install command for the graphql api 
php artisan bagisto-graphql:install

11. And it did not worked, Am i missing anything?

**Comment by Anmol-Chauhan** [comment]
@BrainClickAdsTeam, 
https://prnt.sc/kX5oWzd_3CeE
Please try Bagisto v2.0.0 and still face any issues then raise your [Ticket](https://bagisto.uvdesk.com/en/customer/create-ticket/)
