### ISSUE TITLE
While doing mass operation getting an inappropriate popup message.

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#254]
**Bagisto - v2.0.0**

**Bagisto-headless-ecommerce  -v2.0.0**

In the FCM -> While doing mass operation getting an inappropriate popup message.

**Please take the reference from the video below -**

 
https://jam.dev/c/f6cae4a2-3f08-43c6-892d-897d3f556be9

**Comment by shivamwebkul** [comment]
https://prnt.sc/Cn9KD1xgsH1Q

**Comment by shivamwebkul** [comment]
Issue fixed

**Comment by nishant-webkul** [comment]
Fixed in v2.2.2

Bagisto - v2.0.0

Bagisto-headless-ecommerce -v2.0.0

Web View:

https://github.com/user-attachments/assets/9e83a42c-0954-41f7-bc42-448d68289f00
