### ISSUE TITLE
Please update the heading to Settings

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#256]
**Bagisto - v2.0.0**

**Bagisto-headless-ecommerce -v2.0.0**

**FCM -**

**Description -**

Please update the heading to Settings.

**Screenshot -**

https://jam.dev/c/a7630153-c4c1-49ef-ab65-023f4a1cba02

**Comment by shivamwebkul** [comment]
![image](https://github.com/user-attachments/assets/1aa87fca-5ccc-460c-8bd0-7f3995d8c831)

issue is fixed

**Comment by nishant-webkul** [comment]
Fixed in v2.2.2

Bagisto - v2.2.2

Bagisto-headless-ecommerce -v2.2.2

Web View:

https://webkul.chatwhizz.com/share/screenshot/66ffa72fa81ac5032b1178a1
