### ISSUE TITLE
While creating the notification unable to save the image

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#257]
**Bagisto - v2.0.0**

**Bagisto-headless-ecommerce -v2.0.0**

**FCM -**

**Description -**

While creating the notification unable to save the image.

**Please take the reference from the video below -**

https://jam.dev/c/5153afaa-1b9e-4c3f-801c-516a31e77b00

**Comment by shivamwebkul** [comment]
issue is fixed
https://webkul.chatwhizz.com/share/view-recording/669523449eef6c06ff85d408

**Comment by nishant-webkul** [comment]
Fixed in v2.2.2

Bagisto - v2.2.2

Bagisto-headless-ecommerce -v2.2.2

Web View:

https://github.com/user-attachments/assets/e6758c88-615b-43b7-957d-7a932a08b2fc
