### ISSUE TITLE
Please add the date calendar in the filter section

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#259]
**Bagisto - v2.0.0**

**Bagisto-headless-ecommerce -v2.0.0**

**FCM -**

**Description -**

Please add the date calendar in the filter section.

**Please take the reference from the screenshot/video below -**

https://jam.dev/c/52708404-81e8-47c9-bb2b-5d448c9305ce

**Comment by nishant-webkul** [comment]
Fixed in v2.2.2

Bagisto - v2.2.2

Bagisto-headless-ecommerce -v2.2.2

Web View:

https://webkul.chatwhizz.com/share/screenshot/66ffb341b7c1c7078b3f26a8
