### ISSUE TITLE
Notification should support the multi-channel

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#260]
**Bagisto - v2.0.0**

**Bagisto-headless-ecommerce -v2.0.0**

**FCM -**

**Description -**

Notification should support the multi-channel.

**Please take the reference from the video below -**

https://jam.dev/c/3931d2ae-9ed9-4a27-87cb-859a6cbf7f57

**Comment by nishant-webkul** [comment]
Fixed in v2.2.2

Bagisto - v2.2.2

Bagisto-headless-ecommerce -v2.2.2

Web View:

https://github.com/user-attachments/assets/d0231352-7922-4935-8eb9-44ff4a12a9cc
