### ISSUE TITLE
Notification should support the multi-locale

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#262]
**Bagisto - v2.0.0**

**Bagisto-headless-ecommerce -v2.0.0**

**FCM -**

**Description -**

Notification should support the multi-locale.

**Please take the reference from the screenshot/video below -**

https://jam.dev/c/d5786ecd-db47-4a39-a922-dcfd5873f309

**Comment by nishant-webkul** [comment]
@mayank-webkul please check the issue. Added data in the other local is also updated on the default locale.

Bagisto - v2.2.2

Bagisto-headless-ecommerce -v2.2.2

Web View:

https://github.com/user-attachments/assets/78a66c1e-3f2a-43b1-a645-eee30bd94618

**Comment by nishant-webkul** [comment]
Fixed.

Bagisto - v2.2.2

Bagisto-headless-ecommerce -v2.2.2

Web View:

https://github.com/user-attachments/assets/1b1ed188-0223-4aa6-a46d-7019c57e8a49
