### ISSUE TITLE
If the status of the notification is disabled then the notification should not be sent to the users

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#263]
**Bagisto - v2.0.0**

**Bagisto-headless-ecommerce -v2.0.0**

**FCM -**

**Description -**

If the status of the notification is disabled then the notification should not be sent to the users.

**Please take the reference from the video below -**

https://jam.dev/c/84cb4054-175a-45b3-a659-6a0e6f64f030

**Comment by shivamwebkul** [comment]
![image](https://github.com/user-attachments/assets/2e940018-c80d-4c3a-bc63-e3f0b5993b56)


issue is fixed

**Comment by nishant-webkul** [comment]
@mayank-webkul please recheck this issue. Now "Send Notification" button is not visible in the enable notification.

Bagisto - v2.2.2

Bagisto-headless-ecommerce -v2.2.2

Web View:

https://github.com/user-attachments/assets/2318dc1b-bed8-4811-aa63-0278f83fdbee

**Comment by mayank-webkul** [comment]
@nishant-webkul Kindly check the private key as well in the GraphQL API configuration.
