### ISSUE TITLE
Unable to update the notification -> unable to update the channel of the created notification

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#265]
**Bagisto - v2.0.0**

**Bagisto-headless-ecommerce -v2.0.0**

**FCM -**

**Description -**

Unable to update the notification -> unable to update the channel of the created notification.

**Please take the reference from the video below -**

https://jam.dev/c/28a71312-51d5-47b1-b4d5-399b12ac6b53

**Comment by nishant-webkul** [comment]
@mayank-webkul please recheck this issue in v2.2.2

Bagisto - v2.2.2

Bagisto-headless-ecommerce -v2.2.2

Web View:

https://github.com/user-attachments/assets/9e4efb15-d623-48e4-8a60-780281d4b146

**Comment by nishant-webkul** [comment]
Fixed.

Bagisto - v2.2.2

Bagisto-headless-ecommerce -v2.2.2

Web View:

https://github.com/user-attachments/assets/8b871612-6103-4ee2-a142-00b7973ab682
