### ISSUE TITLE
In the notification, I have selected the Notification type - simple but in the datagrid Notification type is showing Others

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#266]
**Bagisto - v2.0.0**

**Bagisto-headless-ecommerce -v2.0.0**

**FCM -**

**Description -**

In the notification, I have selected the Notification type - simple but in the datagrid Notification type is showing Others.

**Please take the reference from the video below -**

https://jam.dev/c/9d43621f-ffff-4239-b315-b2971c603ef9

**Comment by shivamwebkul** [comment]
![image](https://github.com/user-attachments/assets/b011a95d-455e-4000-8dd4-792d38cdd2de)


issue is dixed

**Comment by nishant-webkul** [comment]
Fixed in v2.2.2

Bagisto - v2.2.2

Bagisto-headless-ecommerce -v2.2.2

Web View:

https://github.com/user-attachments/assets/c8e7115c-ee12-4fd2-b1cc-1c039082e263
