### ISSUE TITLE
Misspelling in AttributeMutation.php

### ISSUE THREAD

**Issue by Diverti** [bagisto/headless-ecommerce#270]
I just wanted to let you know, there is a misspelling in the AttributeMutation.php.
It's really a minor issue, just for code clearance, this function and its references have this name: 
**manageAttribnuteOptions**
instead of
**manageAttributeOptions**

Thanks!

**Comment by vivek-webkul** [comment]
Hi @Diverti,

Thank you for pointing out the misspelling issue. I’ve made the necessary corrections, and it won’t impact your project.

You can pull the latest changes from the following commit: [Fixed Commit Link](https://github.com/bagisto/headless-ecommerce/commit/eaab9108a0d0506d2efb88c2bada9f35915aa844).
