### ISSUE TITLE
Undefined array key "icon"

### ISSUE THREAD

**Issue by elienhd** [bagisto/headless-ecommerce#272]
![image](https://github.com/user-attachments/assets/1ffd0223-2bce-4824-8f8e-0ae4440c9ea8)
i am getting this error after downloading Laravel eCommerce Reward Points, Bagisto version V2.2.2
Undefined array key "icon" (View: C:\xampp\htdocs\example-store\packages\Webkul\Admin\src\Resources\views\components\layouts\header\index.blade.php) (View: C:\xampp\htdocs\example-store\packages\Webkul\Admin\src\Resources\views\components\layouts\header\index.blade.php) (View: C:\xampp\htdocs\example-store\packages\Webkul\Admin\src\Resources\views\components\layouts\header\index.blade.php)

how to solve it ?

**Comment by mayank-webkul** [comment]
@elienhd It seems you might be using an older version of the reward point extension, which isn't compatible with Headless eCommerce v2.2.2. This is likely the cause of the issue you're experiencing.

**Comment by mayank-webkul** [comment]
@elienhd For assistance with this matter, please reach out to our sales team. You can contact them via email at:

sales@webkul.com

They will be able to provide the support you need.
