### ISSUE TITLE
when try to install 

### ISSUE THREAD

**Issue by sanjymaurya201** [bagisto/headless-ecommerce#274]
Root package 'bagisto/graphql-api' cannot require itself in its composer.json
![image](https://github.com/user-attachments/assets/ca7e6685-96df-461c-b302-2863f36dbf82)

**Comment by mayank-webkul** [comment]
Hi, @sanjymaurya201 this issue occurs when the package defined as the root package in your project is also listed as a dependency in its composer.json file. This creates a circular dependency, which Composer cannot resolve.

So, clone the repository anywhere else.
