### ISSUE TITLE
Cart Details Are Empty for Guest Users

### ISSUE THREAD

**Issue by ajayjoshioutdosolutions** [bagisto/headless-ecommerce#281]
I have encountered an issue where cart details are not being displayed correctly for guest users. Here’s a summary of the problem:

**1. Steps to Reproduce:**

Add items to the cart without logging in.
Attempt to access the cart details.

**2. Expected Behavior:**

The cart details should display the items that were added.

**3. Actual Behavior:**

The cart details show an empty or null response for guest users.
The cart functionality works as expected for logged-in users.

**Additional Information:**

Cart items are successfully added when the user is not logged in.
The issue is specifically with retrieving and displaying cart details for guest users.

**Environment**:

Bagisto 2.2.2
GraphQL Headless

Please suggest what might be going wrong or if there might be a missed configuration. I have followed the instructions for installing the GraphQL Headless package.

**Comment by mayank-webkul** [comment]
@ajayjoshioutdosolutions This issue has been resolved.

Commit Link:- [Here](https://github.com/bagisto/headless-ecommerce/pull/280/commits/79c13c2de53f528dedd747824fd953ff6b2429c8)
