### ISSUE TITLE
Created theme is not visible at the web end.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#303]
Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Admin > Settings > Theme > Create

Postman View:

https://github.com/user-attachments/assets/b89a76cd-e4dc-4599-a290-63c7331a2261

**Comment by mayank-webkul** [comment]
@nishant-webkul This will show when you update the same.

**Comment by nishant-webkul** [comment]
ok
