### ISSUE TITLE
Getting "Internal Server Error" if update the theme.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#304]
Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Admin > Settings > Theme > Update

Postman View:

![Screenshot from 2024-09-27 11-57-35](https://github.com/user-attachments/assets/b0c04a4b-5ea4-4823-b269-ff1f139f0990)

**Comment by mayank-webkul** [comment]
@nishant-webkul Kindly let me know the case currently I am not facing any issue while updating the theme.

**Comment by nishant-webkul** [comment]
Fixed.

Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Admin > Settings > Theme > Update

Postman View:

![Screenshot from 2024-10-04 12-33-08](https://github.com/user-attachments/assets/d14b004f-4300-4619-b33a-1b0fe6c1e95c)
