### ISSUE TITLE
Show status "null" when create the shipment at the admin end.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#308]
Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Admin > Sales > Shipments > Create Shipment

API- Admin > Sales > Shipments > Shipments

API- Admin > Sales > Shipments > Shipment

API- Admin > Sales > Orders > Order's Shipments

API- Admin > Sales > Orders > Order's Shipment

Create Shipment Postman View:

![Screenshot from 2024-09-27 16-20-32](https://github.com/user-attachments/assets/96916a6e-6de2-4539-923e-b8d229a6ce56)

Shipments Postman View:

![Screenshot from 2024-09-27 16-28-18](https://github.com/user-attachments/assets/b6362f2d-a504-4c94-b1e8-92458b53ff7a)

Shipment Postman View:

![Screenshot from 2024-09-27 16-28-57](https://github.com/user-attachments/assets/af1e20c1-dce8-44a6-9ca9-9b7682d4feb5)

Order's Shipments Postman View:

![Screenshot from 2024-09-27 17-23-36](https://github.com/user-attachments/assets/f780cc1b-6e2b-4ef6-a4e0-c93ce16b7409)

Order's Shipment Postman View:

![Screenshot from 2024-09-27 17-24-08](https://github.com/user-attachments/assets/2117127e-ac0e-4e3d-a841-4a55bded8cd3)

**Comment by mayank-webkul** [comment]
@nishant-webkul The issue is that the status data isn't being saved in the status column as it is in core Bagisto, resulting in a `null` value.

**Comment by nishant-webkul** [comment]
okay
