### ISSUE TITLE
Getting "please check the shipping address" message in the store order api.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#311]
Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Admin > Sales > Reorder > Store Order

Postman View:

![Screenshot from 2024-09-27 18-37-46](https://github.com/user-attachments/assets/faca78e2-5e6c-4da1-9462-6fc6ed52794f)

**Comment by mayank-webkul** [comment]
@nishant-webkul You can't place an order for the stockable item without providing a shipping address.

**Comment by nishant-webkul** [comment]
Fixed.

Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Admin > Sales > Reorder > Store Order

Postman View:

![Screenshot from 2024-10-22 16-33-19](https://github.com/user-attachments/assets/03c170b0-ba25-4f7b-880c-e750df94af0c)
