### ISSUE TITLE
Need to optimize the sign up api response time.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#312]
Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Session > sign up

Search Engine > Database

Postman View:

![Screenshot from 2024-10-01 11-12-38](https://github.com/user-attachments/assets/aeca2294-54fe-4fe3-b19d-e78bdddfbddb)

**Comment by mayank-webkul** [comment]
@nishant-webkul kindly check the screenshot below.

![Screenshot from 2024-10-03 15-35-51](https://github.com/user-attachments/assets/ddbdb85c-2a93-4749-8f64-75a06a3f300b)
