### ISSUE TITLE
Need to optimize the response time for the social sign up api.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#315]
Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Session > social signup

Search Engine > Database

Postman View:
![Screenshot from 2024-10-01 11-36-57](https://github.com/user-attachments/assets/0b361592-c616-475e-af76-ce39248017ca)

**Comment by mayank-webkul** [comment]
@nishant-webkul kindly check the screenshot below.

![Screenshot from 2024-10-03 15-43-40](https://github.com/user-attachments/assets/53cbc472-d62d-40b4-b4af-97e970373927)

**Comment by nishant-webkul** [comment]
Fixed.

Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Session > social signup

Search Engine > Database

Postman View:

![Screenshot from 2024-10-22 16-38-50](https://github.com/user-attachments/assets/9ae6be58-6a33-465f-afb6-2874ed0efce2)
