### ISSUE TITLE
Need to optimize the response time for the update profile api.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#316]
Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Customer > Account > Profile > Update

Search Engine > Database

Postman View:

![Screenshot from 2024-10-01 12-16-56](https://github.com/user-attachments/assets/bc87a94a-cdd2-429d-a644-453064a55fac)

**Comment by mayank-webkul** [comment]
@nishant-webkul kindly check the screenshot below.

![Screenshot from 2024-10-03 15-45-17](https://github.com/user-attachments/assets/5c3681d6-90ce-447a-bde6-2dbff2a42ea3)

**Comment by nishant-webkul** [comment]
Fixed.

Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Customer > Account > Profile > Update

Search Engine > Database

Postman View:

![Screenshot from 2024-10-22 16-40-57](https://github.com/user-attachments/assets/f82c853b-a291-4ad5-8e35-d86dca992a59)
