### ISSUE TITLE
Need to improve the response time for the forget password api if smtp is not configured.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#318]
Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Customer > Account > Profile > Forget Password

Search Engine > Database

Postman View:

![Screenshot from 2024-10-01 12-29-00](https://github.com/user-attachments/assets/1d8fbe3f-8116-4347-b49e-b1eda2b49330)

**Comment by mayank-webkul** [comment]
@nishant-webkul Kindly check the screenshot below.

![Screenshot from 2024-10-03 16-06-29](https://github.com/user-attachments/assets/1acd3508-7411-4d5f-ac40-b44c08968efd)

**Comment by nishant-webkul** [comment]
Fixed.

Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Customer > Account > Profile > Forget Password

Search Engine > Database

Postman View:

![Screenshot from 2024-10-22 16-43-52](https://github.com/user-attachments/assets/6af36719-b62d-4c81-918b-382abcb66092)
