### ISSUE TITLE
Need to optimize the add to cart product api response time.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#323]
Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Cart > Add to Cart

Search Engine > Database

Postman View:

![Screenshot from 2024-10-01 13-31-31](https://github.com/user-attachments/assets/e949c2c0-45e4-4725-9dcc-df44b18d8cac)

**Comment by mayank-webkul** [comment]
@nishant-webkul Kindly check the screenshot below.

![Screenshot from 2024-10-03 16-30-32](https://github.com/user-attachments/assets/0606e95e-a67b-4e0e-ad54-03baabd2ce9f)

**Comment by nishant-webkul** [comment]
Fixed.

Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Cart > Add to Cart

Search Engine > Database

Postman View:

![Screenshot from 2024-10-22 16-53-34](https://github.com/user-attachments/assets/f8766627-684a-4248-955a-8a3c95ba7e54)
