### ISSUE TITLE
Need to optimize response time for the cart api.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#324]
Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Cart > Cart

Search Engine > Database

Postman View:
![Screenshot from 2024-10-01 13-35-08](https://github.com/user-attachments/assets/4d4a3bb6-387d-42fc-8a52-819c5806bcb5)

**Comment by mayank-webkul** [comment]
@nishant-webkul kindly check the screenshot below.

![Screenshot from 2024-10-03 16-34-59](https://github.com/user-attachments/assets/5e95ebf1-da83-473d-ba91-99fd64f3815e)
