### ISSUE TITLE
Need to optimize response time for the move item to wishlist api.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#325]
Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Cart > Move Item To Wishlist

Search Engine > Database

Postman View:

![Screenshot from 2024-10-01 13-37-35](https://github.com/user-attachments/assets/88d60539-3883-4f4e-ba52-7a56de666342)

**Comment by mayank-webkul** [comment]
@nishant-webkul Kindly check the screenshot below.

![Screenshot from 2024-10-03 16-36-36](https://github.com/user-attachments/assets/051f0a2c-209f-487b-b67e-c661567034fb)

**Comment by nishant-webkul** [comment]
Fixed.

Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Cart > Move Item To Wishlist

Search Engine > Database

Postman View:

![Screenshot from 2024-10-22 17-41-44](https://github.com/user-attachments/assets/583c4baa-fa94-4614-a4c4-d3253486a277)
