### ISSUE TITLE
Getting "internal Server Error" in the Save Address api in case of guest checkout.

### ISSUE THREAD

**Issue by nishant-webkul** [bagisto/headless-ecommerce#334]
Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Checkout > Save Address

Search Engine > Database

Postman View:

https://github.com/user-attachments/assets/a350b7de-9804-474a-a330-06cc524b6548

**Comment by mayank-webkul** [comment]
@nishant-webkul If the cart does not contain any items that can be checked out as a guest, you will not be able to proceed.

**Comment by nishant-webkul** [comment]
Fixed.

Bagisto - v2.2.2

headless-ecommerce - v2.2.2

API- Shop > Checkout > Save Address

Search Engine > Database

Postman View:

![Screenshot from 2024-10-22 18-33-13](https://github.com/user-attachments/assets/db6262c8-a205-498b-8758-66760b31e438)
