### ISSUE TITLE
Undefined array key "filters" error in HomePageQuery.php on line 100 in the Bagisto GraphQL API

### ISSUE THREAD

**Issue by mebron** [bagisto/headless-ecommerce#350]
"What could be causing the Undefined array key "filters" error in HomePageQuery.php on line 100 in the Bagisto GraphQL API for my site, Could it be due to an uninitialized or missing array element in the query logic, or a misconfiguration in the GraphQL query setup?"

This could help guide you to look into how the filters key is being accessed and initialized within your query logic. Let me know if you need further assistance!

**Comment by mayank-webkul** [comment]
>**Issue Fixed**

>PR Link:- [Headless Ecommerce PR #351](https://github.com/bagisto/headless-ecommerce/pull/351)
