### ISSUE TITLE
JS on storefront

### ISSUE THREAD

**Issue by erezson** [bagisto/headless-ecommerce#37]
Hi Bagistos!

We want to develop an integration for Bagisto and we need to have the option to add custom JS on storefront. Can you please point me to the relevant API?

**Comment by naresh-webkul** [comment]
Hi,
We already have the option to add custom js/css on the store front from the admin panel. you can check under the configuration menu and the content tab. there is a option for custom scripts , but relevent to api this option is not available for now, you can raise a pr for this .
https://prnt.sc/1252mpu
Thanks!

**Comment by naresh-webkul** [comment]
Hi @erezson ,
We are working to implement the API for same , by Monday or Tuesday you can check for the updated code.
Thanks!

**Comment by erezson** [comment]
Thanks a lot for the update!

**Comment by vivek-webkul** [comment]
Implemented.

**Comment by erezson** [comment]
Hey @vivek-webkul & @naresh-webkul 

Looks like users needs to have the graphql api package installed for our app to be able to add code in the relevant place. But this package is not installed by default. 

Is there any work around for it? correct me if I'm wrong of course :)
