### ISSUE TITLE
No commands defined in the "bagisto_graphql" namespace.

### ISSUE THREAD

**Issue by alexbuce** [bagisto/headless-ecommerce#40]
C:\xampp7\htdocs\bagisto>composer dump-autoload
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: astrotomic/laravel-translatable
Discovered Package: babenkoivan/elastic-client
Discovered Package: babenkoivan/elastic-scout-driver
Discovered Package: bagisto/bagisto-package-generator
Discovered Package: bagistobrasil/bagisto-product-social-share
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: fideloper/proxy
Discovered Package: flynsarmy/db-blade-compiler
Discovered Package: intervention/image
Discovered Package: kalnoy/nestedset
Discovered Package: konekt/concord
Discovered Package: konekt/enum-eloquent
Discovered Package: laravel/scout
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: maatwebsite/excel
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: prettus/l5-repository
Discovered Package: tymon/jwt-auth
Package manifest generated successfully.
Generated optimized autoload files containing 8817 classes

C:\xampp7\htdocs\bagisto>php artisan bagisto_graphql:install

  There are no commands defined in the "bagisto_graphql" namespace.

**Comment by vivek-webkul** [comment]
@alexbuce & @merdiano 

Readme file updated for this issue:
https://github.com/bagisto/headless-ecommerce#run-the-below-mentioned-commands-from-the-root-directory-in-terminal
