### ISSUE TITLE
Product update mutation not working properly

### ISSUE THREAD

**Issue by tarunwebkul** [bagisto/headless-ecommerce#41]
I am trying create a product on bagisto with graphql product create mutation but have not found the way to pass name so product created without name on bagisto, And Update mutation also not working
so product name and description not getting update and inventory and price of the product update work fine.
Facing this issue for simple and configurable product

**Comment by naresh-webkul** [comment]
Hi,
Not getting such issue , working fine create and update product mutation.

**Comment by vivek-webkul** [comment]
@tarunwebkul 
In product creation mutation, Bagisto only used ProductType, Attributefamily, and SKU these fields, If you wish to use the name in product mutation, you have to use Update mutation:

**To Create product Mutation:** https://github.com/bagisto/headless-ecommerce/blob/main/Postman_APIs/Collections/Catalog.postman_collection.json#L647

**To Update product Mutation:** https://github.com/bagisto/headless-ecommerce/blob/main/Postman_APIs/Collections/Catalog.postman_collection.json#L674

For more help, you can use provided Postman APIs collection.
