### ISSUE TITLE
Replace images files hosted externally in README.md

### ISSUE THREAD

**Issue by derMart** [bagisto/headless-ecommerce#42]
Please, by all means convert those images files:
`https://prnt.sc/y03ye5` etc. in the README.md to machine readable text, which is not hosted externally!

**Comment by vivek-webkul** [comment]
@derMart 
Images replaced with the code:
Commit Link: https://github.com/bagisto/headless-ecommerce/commit/e3757b2cc660e0b63cb6f433220ad8be4ea60ba1

Closing this issue now.
