### ISSUE TITLE
Link to download and install it, must availbale in bagisto doc 

### ISSUE THREAD

**Issue by Anmol-Chauhan** [bagisto/headless-ecommerce#43]
https://devdocs.bagisto.com/1.x/graphql-admin-api/

**Comment by vivek-webkul** [comment]
@Anmol-Chauhan 
Updated GraphQL API Doc: 
https://devdocs.bagisto.com/1.x/graphql-admin-api/#bagisto-graphql-admin-apis
https://devdocs.bagisto.com/1.x/graphql-admin-api/installation.html
