### ISSUE TITLE
Error after updating Bagisto to 1.3.3 (from Product::getTypeInstance())

### ISSUE THREAD

**Issue by funder7** [bagisto/headless-ecommerce#44]
Hi,

After updating my project by merging Bagisto `v1.3.3`, the project became broken due to this error:

```
> @php artisan package:discover

PHP Fatal error:  Declaration of Webkul\GraphQLAPI\Models\Catalog\Product::getTypeInstance() must be compatible with Webkul\Product\Models\Product::getTypeInstance(): Webkul\Product\Type\AbstractType in /var/www/html/packages/Webkul/GraphQLAPI/Models/Catalog/Product.php on line 21
```

I'm sending a PR in the next minutes to fix the issue. 

Cheers!

**Comment by vivek-webkul** [comment]
There are no such issues in the main branch, Closing this issue.

**Comment by funder7** [comment]
Have you tried to install the package into bagisto 1.3.3? 
I did, and it was not running until this fix was applied.
