### ISSUE TITLE
Issues with GraphQL API in a  fresh bagisto installation 

### ISSUE THREAD

**Issue by AxilleasMoukoulis** [bagisto/headless-ecommerce#47]
Hello,

I'm new to laravel and bagisto and i would like to request your assistance on the following issue that i'm facing. I have installed bagisto in a docker container (it includes all the prerequisites) and it works as expected. However, i would like to have admin access via API in order to be able to manipulate customer profiles (add, update, remove e.t.c ) from another app. After consulting the documentation, i've stumbled upon the GraphQLAPI that bagisto offers. So, i've proceeded with the installation as instructed in bagisto/headless-ecommerce. Please find below my steps:
![Screenshot 2021-12-01 at 3 54 07 PM](https://user-images.githubusercontent.com/16209784/144261221-5d22a48c-caf1-4105-ad4d-8a7dc383a93f.png)

![Screenshot 2021-12-01 at 3 55 30 PM](https://user-images.githubusercontent.com/16209784/144261291-f0e513cf-8979-41de-8610-31bae9e6f662.png)

![Screenshot 2021-12-01 at 3 58 51 PM](https://user-images.githubusercontent.com/16209784/144261302-e77d4805-f9b9-4dee-8cbc-415275986faf.png)

Then,

![Screenshot 2021-12-01 at 4 01 16 PM](https://user-images.githubusercontent.com/16209784/144261357-99ec8778-93bc-48b7-9f3e-f7d0914badc7.png)
![Screenshot 2021-12-01 at 4 01 36 PM](https://user-images.githubusercontent.com/16209784/144261372-517679f7-1505-4ed3-a66e-16d3e9204103.png)
![Screenshot 2021-12-01 at 4 01 51 PM](https://user-images.githubusercontent.com/16209784/144261381-f485c7b8-5202-4b6a-92ff-450f575a3132.png)

And finally,

![Screenshot 2021-12-01 at 4 03 55 PM](https://user-images.githubusercontent.com/16209784/144261458-bbc9af76-8e1e-4708-93e2-a4e76da263d2.png)

![Screenshot 2021-12-01 at 4 04 56 PM](https://user-images.githubusercontent.com/16209784/144261478-d666d949-3aed-4441-a76e-c2dbca778a47.png)

![Screenshot 2021-12-01 at 4 06 00 PM](https://user-images.githubusercontent.com/16209784/144261493-fde1c6cb-b561-4054-8fb5-02ba9fc0f065.png)

Unfortunately, i'm unable to access the graphql API. Below you may find the errors that i'm receiving both in Postman and GraphQL Playground

<img width="1007" alt="Screenshot 2021-12-01 at 3 50 07 PM" src="https://user-images.githubusercontent.com/16209784/144261648-5e582506-e754-421e-89a9-d09f7661dd09.png">

<img width="1191" alt="Screenshot 2021-12-01 at 3 52 28 PM" src="https://user-images.githubusercontent.com/16209784/144261676-d21f64d8-a56d-4dd8-be73-6c96cb8c6536.png">

Could you kindly let me know if i'm missing any essential step during the process? Thank you very much for your time.

**Comment by vivek-webkul** [comment]
@AxilleasMoukoulis 
Can you please let us know your Bagisto version?

**Comment by AxilleasMoukoulis** [comment]
Hello Vivek,

Thank you very much for your time and the correction that you've pointed out. After trying to troubleshoot the issue, i noticed that the GraphQL route wasn't listed in the routes list of the project. 

php artisan route:list

So, i executed the below commands and the issue was resolved:

php artisan config:cache
php artisan route:cache

Now i'm able to access the API from a python client. Maybe you could mention this additional step in the instructions in case anyone has a similar issue. Once again, thank you very much for you time.

**Comment by vivek-webkul** [comment]
@AxilleasMoukoulis 
Thanks for your suggestion, for sure I will update the user guide.
