### ISSUE TITLE
how can i override mutation

### ISSUE THREAD

**Issue by Jatinkabariya** [bagisto/headless-ecommerce#55]
i want to modify query [ remove password field from query ], and remove below exception handling in /src/Mutations/Shop/Customer/SessionMutation.php file
       `throw new CustomException(
                trans('shop::app.customer.login-form.invalid-creds'),
                'Invalid Email and Password.'
            );`
and return custom message on invalid credentials,
because above exaptation send error on invalid credentials.

**Comment by ashishkumar-webkul** [comment]
@Jatinkabariya 
You can  create your own mutation and extend your default query, once this is done, you can call the mutation.
