### ISSUE TITLE
Interface "Tymon\JWTAuth\Contracts\JWTSubject" not found

### ISSUE THREAD

**Issue by naramwork** [bagisto/headless-ecommerce#56]
I'm stuck in this 
I follow the steps on the docs and always lead to this error

<img width="1533" alt="Screen Shot 2022-04-13 at 11 43 32 AM" src="https://user-images.githubusercontent.com/90054075/163137411-cdacd6e4-d4df-40a6-b662-d36323e8f7a2.png">
 
should I install jwt manually ?

**Comment by devlamine** [comment]
I have same error and when I install manualy I have this message : 

`eclaration of Webkul\GraphQLAPI\Models\User\Admin::getJWTCustomClaims() must be compatible with Webkul\User\Models\Admin::getJWTCustomClaims(): array

  at vendor/bagisto/graphql-api/src/Models/User/Admin.php:53
     49▕      * Return a key value array, containing any custom claims to be added to the JWT.
     50▕      *
     51▕      * @return array
     52▕      */
  ➜  53▕     public function getJWTCustomClaims()
     54▕     {
     55▕         return [];
     56▕     }
     57▕ }`

**Comment by vivek-webkul** [comment]
Hi @naramwork & @devlamine 
Please mention your Bagisto version also.

**Comment by devlamine** [comment]
hi, @vivek-webkul  v1.4.1

**Comment by vivek-webkul** [comment]
Hi @devlamine 

Currently, this project supports Bagisto v1.3.x
https://github.com/bagisto/headless-ecommerce#1-requirements

We will provide support for 1.4.x very soon.

**Comment by rzuzo** [comment]
Hello, are there maybe any updates for the 1.4.x support? 

We are setting up the bagisto laravel shop with a vue storefront and encountered the same error as mentioned by @naramwork .

Thanks

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the Issue is Fixed and Just what is need to be done just after the bagisto installation run the command

**composer require bagisto/graphql-api:dev-main**

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/189622744-718fcb3c-5369-466f-91f8-bde2b3e2db90.mp4
