### ISSUE TITLE
Bagisto GraphQL Shop API: Get Customer Orders ERROR: "Cannot query field \"id\" on type \"OrderPaginator\"."

### ISSUE THREAD

**Issue by daniilevstafyev-dev** [bagisto/headless-ecommerce#58]
Hello! I've followed your documentations ( https://devdocs.bagisto.com/1.x/graphql-shop-api/orders.html#get-customer-orders ) to queries but I got this error in my localhost. Btw, the documentation is partially outdated. Any help will be much appreciated. Thanks.

For example, the simplest graphql query for orders: (the problem so far is only in orders, in other requests everything is okay)
`query ordersList {
      ordersList(input: {
          orderDate: "2022-06-12"
      }) {
          id
      }
  }`

And I got:
`{
  "errors": [
    {
      "message": "Cannot query field \"id\" on type \"OrderPaginator\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}`

PS: Now I checked other requests in the Bagisto GraphQL Shop API, they also do not work, requests only work in the Bagisto GraphQL Admin API

PS2: It looks like I understood what the problem is, we need the old version of the bagisto, namely v1.3. Version 1.4 not supported...

![Screenshot from 2022-06-24 09-47-52](https://user-images.githubusercontent.com/76105596/175453354-882ca4fd-9a09-408c-9808-ed2ee2146bde.png)

**Comment by vivek-webkul** [comment]
@daniilevstafyev-dev 

The orderlist API will return the response object and you are trying to get the id directly.
Kindly use data {} object.

![orderlist](https://user-images.githubusercontent.com/28401696/190105023-41a1118c-963f-47d9-a1b0-33916252563e.png)
