### ISSUE TITLE
We are unable to update the CMS Page via API.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#64]
## Issue Description
When we try to update the CMS Page via API, we are getting internal server error and undefined array key issue.

## Bagisto Version
V1.4.3

## Steps To Reproduce
1. Go to Postman -> CMS API Collection -> Update CMS Page API 
2. There when we fill the data and hit the API, then we can see the error appearing.

## Actual Result
Please check the below screenshots for a better understanding of the concern.

**POSTMAN COLLECTION**
![Screenshot from 2022-08-22 13-14-15](https://user-images.githubusercontent.com/92721837/185867636-f6512c97-2fc5-4464-87d7-70c8eb776c64.png)

## Expected Result
We should be able to update the details of the CMS page API without any error.

**Comment by deepaksinghgusain227** [comment]
This issue is due to cms collection. CMS collection is updated - https://github.com/bagisto/headless-ecommerce/pull/89/commits/cafe9cb8a34ae64b2f41fbfa8967fed5d6d6c314

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/189289710-352a6b07-4c35-4524-8d4f-f25728e246af.mp4
