### ISSUE TITLE
Category Logo details must be added in the API Query for Create New Category.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#65]
## Issue Description
When we check the details of creating the Category with the help of API, there we are unable to see the Category logo details. Please add the category logo details in the API also.

## Bagisto Version
V1.4.3

## Steps To Reproduce
1. Go to Postman -> Catalog  -> Categories Section -> Create a new Category. 
2. There we can see that the details of the Category logo is missing.

## Actual Result
Please check the below screenshots for a better understanding of the concern.

**POSTMAN COLLECTION**
![Screenshot from 2022-08-22 13-25-17](https://user-images.githubusercontent.com/92721837/185870006-d4492ef7-c30d-43fd-8b8f-7ef293d863df.png)

**ADMIN SECTION**
![Screenshot from 2022-08-22 13-25-20](https://user-images.githubusercontent.com/92721837/185870024-d74070a8-b536-40a8-9529-aa5d4470b73a.png)

## Expected Result
There should be the option to add image in the logo as well.

**Comment by deepaksinghgusain227** [comment]
added in commit id - 2f957d6f919ea30ea09174e59a08738adfbebf27

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/189291033-572fd2ea-eb52-4851-8feb-380b34a8870b.mp4
