### ISSUE TITLE
In Bundle and Group Product Update we are able to add Virtual and Downloadable Product.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#68]
## Issue Description
After creating the Bundle and Group Product, there in Update  bundle and Group Product, when we fill the details of the downloadable product and virtual product in the API, it passes the action and in front end we are able to see the Downloadable and virtual product added in the Group and Bundle Product.

## Bagisto Version
**V1.4.3**

## Steps To Reproduce
1. Go to Postman -> Catalog API Collection -> Products Section -> Update Bundle and Group Product. 
2. There when we fill the data and hit the API, then we can see that the Downloadable and Virtual Product are also passed in the API.
3.  In front end when we check the product we can see them added.

## Actual Result
Please check the below screenshot and video for a better understanding of the concern.

**POSTMAN COLLECTION**
![Screenshot from 2022-08-22 17-30-11](https://user-images.githubusercontent.com/92721837/185916349-884e32d8-7a1c-40d9-a01b-c0a7c9a7ec40.png)

**Video**

https://user-images.githubusercontent.com/92721837/185916371-16adefbf-7e04-455e-bc9a-5642d07e126e.mp4

## Expected Result
As per the functionality of the bundle and group product only simple products are added in them. And here we  are able to add the virtual and downloadable product to the bundle and group product.

**Comment by deepaksinghgusain227** [comment]
Fixed in commit id - da1a06b8bea7008d59d794d1331daa5e29ae00c7

**Comment by ashishkumar-webkul** [comment]
**Bagisto - V1.4.3**

Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**


https://user-images.githubusercontent.com/92721837/189633746-37909b33-1619-4f87-91a9-bdba306308a7.mp4
