### ISSUE TITLE
In Appointment Booking the Update API is not working Properly. Product is showing OUT OF STOCK.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#69]
## Issue Description
After creating the Appointment Product and the updating the product, when we fill all the information related to the Appointment booking, and then hit the API, we can see that the product is showing OUT OF STOCK and also the dated we have set are not accurate.

## Bagisto Version
**V1.4.3**

## Steps To Reproduce
1. Go to Postman -> Catalog API Collection -> Products Section -> Update Appointment Booking Product. 
2. There when we fill the data and hit the API, then we can see that the appointment booking product is showing OUT OF STOCK .
3.  And also we have entered the details of Same Slot for all days  and in front end it is showing particular days details.

## Actual Result
Please check the below  video for a better understanding of the concern.

**Video**

https://user-images.githubusercontent.com/92721837/185923128-fef1a672-fa1d-4428-9128-ec9254f50ee2.mp4

## Expected Result
The working should be simple as when we select same slot for all days that means each days will have same time slot and if we select different time for different product then that must go the same way.

**Comment by deepaksinghgusain227** [comment]
Fixed in commit id - da1a06b8bea7008d59d794d1331daa5e29ae00c7

**Comment by ashishkumar-webkul** [comment]
**Bagisto - V1.4.3**

Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**


https://user-images.githubusercontent.com/92721837/189637487-3edc04d0-83d4-4f3f-8fbd-4526c84bdcac.mp4
