### ISSUE TITLE
In Rental Booking Product - The Rental Booking Product is redirecting to Home Page after the Update from API.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#70]
## Issue Description
After creating the rental Booking product and then updating the same product from the API, then we check the Rental Booking Product in the Front-End, there we can see the product is redirecting to the Home Page.

## Bagisto Version
**V1.4.3**

## Steps To Reproduce
1. Go to Postman -> Catalog API Collection -> Products Section -> Update Rental Booking Product. 
2. There when we fill the data and hit the API, then we can see that the Rental booking product is Redirecting to Home Page. 

## Actual Result
Please check the below  video for a better understanding of the concern.

**Video**

https://user-images.githubusercontent.com/92721837/185926843-28bb7113-5834-4c27-9738-a8f6fe37a88b.mp4

## Expected Result
The working of the Rental Product should be based on the Daily or Hourly Basis and also it should not redirect to the Home Page.

**Comment by deepaksinghgusain227** [comment]
Fixed in commit id - da1a06b8bea7008d59d794d1331daa5e29ae00c7

**Comment by ashishkumar-webkul** [comment]
**Bagisto - V1.4.3**

Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**


https://user-images.githubusercontent.com/92721837/189635799-c1fcd429-1fc0-4604-a28a-d7ca3d9cec8c.mp4
