### ISSUE TITLE
Unable to Create Event Booking Product with the help of API.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#71]
## Issue Description
When we try to create the event booking product, there we are getting the issue. Cannot Query field issue is appearing. 

## Bagisto Version
**V1.4.3**

## Steps To Reproduce
1. Go to Postman -> Catalog API Collection -> Products Section -> Create Event Booking Product. 
2. There when we hit the API and then we face this issue, we are unable to create the Event Booking Product.

## Actual Result
Please check the below  video for a better understanding of the concern.

**Video**

https://user-images.githubusercontent.com/92721837/185930026-59898679-e6b2-4364-95f7-2cba9cb7a182.mp4

## Expected Result
When we hit the API it should create the product.

**Comment by deepaksinghgusain227** [comment]
Fixed in commit id - da1a06b8bea7008d59d794d1331daa5e29ae00c7

**Comment by ashishkumar-webkul** [comment]
**Bagisto - V1.4.3**

Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/189629298-d21883bb-093e-4a7d-a3ee-df136b3aa874.mp4
