### ISSUE TITLE
In Bagisto Marketing Section we have Sitemaps and Email Marketing Section, Need to create the API for the same.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#73]
## Issue Description
In Bagisto Admin Sectin we have marketing section and there we have sub-options, Sitemaps and Email Marketing. We should have the API for them as well.

## Bagisto Version
**V1.4.3**

## Steps To Reproduce
1.  Go to Admin -> Marketing -> Sitemaps and Email Marketing.
2. When we check the Headless API collection we do not have the API for them.

## Actual Result
Please check the below  Screenshots for a better understanding of the concern.

**ADMIN**
![Email](https://user-images.githubusercontent.com/92721837/186092033-9d78922b-b9b1-4228-998e-101bd1d7fb75.png)

**POSTMAN**
Check the mouse cursor
![Screenshot from 2022-08-23 12-30-05](https://user-images.githubusercontent.com/92721837/186092174-a39f3ca5-737d-4623-9465-e539976bcc45.png)

## Expected Result
We need to have the API for them as well.

**Comment by deepaksinghgusain227** [comment]
created api for marketing and sitemap  section in commit id - b31072993bd2dafb7517466b6bc487dc8c373235

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**


https://user-images.githubusercontent.com/92721837/189611911-9c517850-6958-469c-b1b3-eb3b62c5ab70.mp4
