### ISSUE TITLE
We are unable to create the invoice with API. 

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#74]
## Issue Description
We have ordered the product and when we try to create the invoice of the product with the help of API, we are unable to create the invoice.

## Bagisto Version
**V1.4.3**

## Steps To Reproduce
1. Go to POSTMAN -> Sales -> Invoices -> Create Order's Item Invoice.
2. When we fill the data Order ID and Order Item ID, there we are unable to create the invoice.

## Actual Result
Please check the below  video for a better understanding of the concern.

**Video**
https://user-images.githubusercontent.com/92721837/186129100-4035dfd1-7298-41b6-9805-15780994a895.mp4

## Expected Result
The Order must be created when we hit the API.

**Comment by deepaksinghgusain227** [comment]
this issue is working fine. Please check.

**Comment by ashishkumar-webkul** [comment]
**Bagisto - V1.4.3**

Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**


https://user-images.githubusercontent.com/92721837/189625099-ad2689b6-4763-4802-a649-6bc4b0ce03ec.mp4
