### ISSUE TITLE
We are unable to do the Shipment with API.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#75]
## Issue Description
We have ordered the product and when we try to create the Shipment of the product with the help of API, we are unable to create the Shipment.

## Bagisto Version
**V1.4.3**

## Steps To Reproduce
1. Go to POSTMAN -> Sales -> Shipments -> Create Shipment's Item Invoice.
2. When we fill the data Order ID and Order Item ID, there we are unable to create the Shipment.

## Actual Result
Please check the below  video for a better understanding of the concern.

**Video**
https://user-images.githubusercontent.com/92721837/186130888-6b59b676-75ef-4e8e-a6f2-91f9ee3e529b.mp4

## Expected Result
The Shipment must be created when we hit the API.

**Comment by deepaksinghgusain227** [comment]
this issue is working fine. Please check.

**Comment by ashishkumar-webkul** [comment]
**Bagisto - V1.4.3**

Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**


https://user-images.githubusercontent.com/92721837/189641921-6c014ead-aacd-427d-b54e-5e7698e88d8f.mp4
