### ISSUE TITLE
In Shop API - Get Customer Details - We are unable to fetch the details of the customer.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#77]
## Issue Description
When checking the customer details via API, there when we check the Get Customer Details API, we are unable to fetch the data.

## Bagisto Version
**V1.4.3**

## Steps To Reproduce
1. Go to Postman -> Shop API Collection -> Customer Account -> Get Customer Details.
2. Here when we pass the details with customer login Bearer token, we are unable to fetch the data.

## Actual Result
Please check the below  video for a better understanding of the concern.

**Video**

https://user-images.githubusercontent.com/92721837/186337808-a41af2e3-2f78-4e8c-aabd-02e4b3e7c08d.mp4

## Expected Result
The details must appear when we pass the token to the Get Customer Detail API.

**Comment by deepaksinghgusain227** [comment]
this issue is fixed in commit id - https://github.com/bagisto/headless-ecommerce/pull/89/commits/8ca5507b06e1716f7e5dbb7e66aa65503f9c2e34

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**


https://user-images.githubusercontent.com/92721837/189608601-c7a23f4b-a2ba-4a35-9354-35a230cd1e64.mp4
