### ISSUE TITLE
In Shop API - Customer Account - We are unable to Update the details of the Customer Account.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#78]
## Issue Description
When checking the customer details via API, after that when we check the API of the Update customer account in API, we are facing issues while updating the details.

## Bagisto Version
**V1.4.3**

## Steps To Reproduce
1. Go to Postman -> Shop API Collection -> Customer Account -> Update Account Details.
2. Here when we pass the details with customer login Bearer token, we are unable to Update the data.

## Actual Result
Please check the below  video for a better understanding of the concern.

**Video**

https://user-images.githubusercontent.com/92721837/186342172-f0d8d3ae-9c45-49d0-b86b-b47967ea05a4.mp4

## Expected Result
The details must appear when we pass the token to the Update Customer Detail API. The details must be updated as per the data what we have sent.

**Comment by deepaksinghgusain227** [comment]
this issue is working fine in commit id- https://github.com/bagisto/headless-ecommerce/commit/6049dcb78d7641a6fb796b067268d8d479c7d47b

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**


https://user-images.githubusercontent.com/92721837/189606313-dc6916e0-667b-41ba-8f69-2484c3313f4a.mp4
