### ISSUE TITLE
In Shop API - Customer Addresses - We are unable to fetch the data of the customer addresses.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#79]
## Issue Description
When checking the customer details via API, there when we check the Get Customer address API, we are unable to fetch the data.

## Bagisto Version
**V1.4.3**

## Steps To Reproduce
1. Go to Postman -> Shop API Collection -> Customer Addresses -> Get Customer Addresses List.
2. Here when we pass the details with customer login Bearer token, we are unable to fetch the data.
3.  Same I have tried to fetch the data with admin's token then also the same issue.

## Actual Result
Please check the below  video for a better understanding of the concern.

**Video**

https://user-images.githubusercontent.com/92721837/186358470-468add1c-2392-4986-a53a-95aa4c93a8bc.mp4

## Expected Result
The details must appear when we pass the token to Get the Addresses detailed List.

**Comment by deepaksinghgusain227** [comment]
this issue is working fine in commit id- https://github.com/bagisto/headless-ecommerce/commit/6049dcb78d7641a6fb796b067268d8d479c7d47b

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/189359733-4e8f4d4f-71d1-4725-854b-ac321814ff53.mp4
