### ISSUE TITLE
In Shop API - Customer Addresses - We are unable to update the data of the customer addresses.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#80]
## Issue Description
When checking the addresses related concern with the API, and Updating the details of the customer address, we are unable to update the address, after inserting the token and address id.

## Bagisto Version
**V1.4.3**

## Steps To Reproduce
1. Go to Postman -> Shop API Collection -> Customer Addresses -> Update Customer Address.
2. Here when we pass the details with customer login Bearer token, we are unable to update.

## Actual Result
Please check the below  video for a better understanding of the concern.

**Video**

https://user-images.githubusercontent.com/92721837/186364968-a5d0e9a1-cd2c-4866-a537-b649bab9323d.mp4

## Expected Result
The details must updated when we feed the data in the API and then hit it.

**Comment by deepaksinghgusain227** [comment]
this issue is working fine in commit id- https://github.com/bagisto/headless-ecommerce/commit/6049dcb78d7641a6fb796b067268d8d479c7d47b

**Comment by ashishkumar-webkul** [comment]
**Bagisto - V1.4.3**

Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/189640440-6b5e4cdc-cbfe-4964-9b40-990ab1216d6b.mp4
