### ISSUE TITLE
Shop API Collection -> Customer Wishlist -> Unable to Fetch the details of the Customer's Wishlist Details.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#85]
## Issue Description
When checking the list of customer's wishlist Detail and when we are fetching the data of the Detail we are unable to do so, we are getting error for the same.

## Bagisto Version
**V1.4.3**

## Steps To Reproduce
1. Go To Postman -> Shop API Collection -> Customer's Wishlist -> Get Customer Detail.
2. There we are facing some issues in fetching the Data.

## Actual Result
Please check the below  video for a better understanding of the concern.

**Video**

https://user-images.githubusercontent.com/92721837/186395481-602f100f-bc23-44a6-9982-064279a2895d.mp4

## Expected Result
The details must be fetched when checking the details of the wishlist for the customer.

**Comment by deepaksinghgusain227** [comment]
this issue is fixed in commit id - https://github.com/deepaksinghgusain227/headless-ecommerce/commit/ccb049f8ddd4469a6845ac8a5ee90d9b8abdf810

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the Issue is Fixed and now it is working fine, Hence I am closing the issue from my end. I am attaching Video/ Screenshot for the reference. Please consider it.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/189348275-bb929216-a553-4e3d-9db8-f89ecd547200.mp4
