### ISSUE TITLE
Need to Update the details in the Codes for the proper working of the Marketing Section.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#90]
**Bagisto - V1.4.3**

**Description**
When we are checking the details of the Marketing Section there we can see that the details are not appearing for the Sitemaps and Email Templates.
When checking the Codes it was found that the following path is having some data missing.
Need to Add the following data for the proper working of the API.

**PATH -  vendor/bagisto/graphhql-api/src/graphql/schema.graphql**

**Add the following
#import /marketing/*.graphql**

For Reference consider the screenshot

![Screenshot from 2022-09-12 17-44-34](https://user-images.githubusercontent.com/92721837/189665733-df90bbcf-388b-4924-9700-49da5ca1dabc.png)

**Comment by vivek-webkul** [comment]
@ashishkumar-webkul 
Updated, after verifying the same close this issue:
[https://github.com/bagisto/headless-ecommerce/commit/8b05d9ac9f255b5579937d398ab7d979efe74f8f](Fix Commit Link)

**Comment by ashishkumar-webkul** [comment]
Checked the issue after the fresh installation of bagisto and headless. Now it is working fine. Hence I am  closing the issue. Please consider the video for the reference.

**Video**

https://user-images.githubusercontent.com/92721837/190130569-f6754061-219f-4d81-b595-72c43c74c579.mp4
