### ISSUE TITLE
problem when try install

### ISSUE THREAD

**Issue by estige** [bagisto/headless-ecommerce#91]
<img width="859" alt="image" src="https://user-images.githubusercontent.com/100708301/193424537-197db1f1-cd83-4e9f-9b09-3213b8ed5fcd.png">

**Comment by mstdn** [comment]
I face the same issue indeed.

**Comment by vivek-webkul** [comment]
Hi 
@estige & @mstdn 
Greetings,

Can you please let us know which Bagisto version you are using?

Thanks & Regards,
Bagisto Support Team

**Comment by estige** [comment]
Bagisto 1.4.5

**Comment by vivek-webkul** [comment]
Hi @estige 

As I checked you are using version [v1.3.3](https://github.com/bagisto/headless-ecommerce/blob/v1.3.3/src/Models/User/Admin.php) of Headless-ecommerece, In which we override the user's admin model.
And Headless-ecommerece v1.3.3 version is only compatible with Bagisto v1.3.x version, So It will not work with Bagisto v1.4.5.

For Bagisto v1.4.5 you have to pull the code from [Headless-ecommerece main](https://github.com/bagisto/headless-ecommerce#1-requirements) branch.

Thanks & Regards,
Bagisto Support Team

**Comment by msatyao** [comment]
How to do this? 

"For Bagisto v1.4.5 you have to pull the code from Headless-ecommerece main branch"
