### ISSUE TITLE
Interface "Tymon\JWTAuth\Contracts\JWTSubject" not found

### ISSUE THREAD

**Issue by kholbek** [bagisto/headless-ecommerce#92]
## Description
Installation `bagisto/graphql-api` dependency fails.
I've successfully setup and started bagisto v1.4.3, but installing `bagisto/graphql-api` dependency throws an error.
Same issue happens with latest version of bagisto, but the [README](https://github.com/bagisto/headless-ecommerce/blob/main/README.md) says to have v1.4.3.

 ## Steps 
```bash
# Git version 2.37.1 (Apple Git-137.1)
git clone -b v1.4.3 https://github.com/bagisto/bagisto.git
```
```bash
# Composer version 2.4.4 2022-10-27 14:39:29
composer install
```
```bash
# Composer version 2.4.4 2022-10-27 14:39:29
composer require bagisto/graphql-api
```
<img width="854" alt="image" src="https://user-images.githubusercontent.com/116568313/202500837-71f23830-71c6-4c9d-bafb-547e4be8335f.png">

**Comment by vivek-webkul** [comment]
@kholbek 

You can try the latest release v1.4.3 with your Bagisto version (v1.4.3).
