### ISSUE TITLE
This project replaces the rest-api

### ISSUE THREAD

**Issue by gcaraciolo** [bagisto/headless-ecommerce#93]
Hello, I didn't know where to ask this kind of question. If here is not the right place, please let me know.

I just start a feature using bagisto + bagisto multicompany saas.
I will integrate bagisto with an existing project using an Api, and it seems that that are a few options: `legacy-api`, `rest-api` and this one, `headless-ecommerce`.

Which one do you recommend for the long run?

**Comment by vivek-webkul** [comment]
Hello @gcaraciolo ,

Thanks for using our product, You can use anyone from rest-api and headless-ecommerce. We will provide support for both products.

Thanks.
