### ISSUE TITLE
It didn't work with latest version of bagisto 

### ISSUE THREAD

**Issue by Anirudh596** [bagisto/headless-ecommerce#96]
graph api package is not working with latest version of bagisto what are you guys doing you just push the version and didn't see that other functionalities is working or not how incapable you are when i require this on my bagisto project it gives me php-source, illuminate/auth version error and didn't work with any version.
you just wake up and publish the new version and break all at once not had anything in mind that you break your whole package  and trust.

**Comment by saurav-webkul** [comment]
Hi @Anirudh596 ,

We have recently released the updated API package for 2.0. Please check this one: https://github.com/bagisto/headless-ecommerce/tree/v2.0.0

**Comment by Anirudh596** [comment]
Thanks for your generous response now but I'm using strapi instead of bagisto. But for second thought I prefer bagisto as it is full complete package a little bit complex but yeah a full Ecommerce package I've ever seen.
Sorry about that time for being rude, I was really pissed off because I'm at the deadline of a project, when I am configured to my needs and at the time of integration it won't work so i wrote that kind of shit,
Yeah that's how things need to be work 🙂 won't they?
I guess you work as hard as needed but we all need to go with plans so things won't go off. 

Again thank you, I would really consider using bagisto in the future if i got another ecommerce platform to create.

**Comment by saurav-webkul** [comment]
It's okay @Anirudh596 We understand working on an opensource project, we may not fulfill everyone's need at the right time but this is for sure we are continuously working on it. 2.0 is the major release so it has taken time to update the API docs. 

We wish you use bagisto for other e-commerce projects in future. Further if you have any queries or issue, feel free to ping us, we are always there for our community.
