### ISSUE TITLE
Getting exception in Inventory Source API

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/headless-ecommerce#99]
Description -

In the Settings -> Inventory Source API ->

**Create New Inventory Source API -** Getting exception if created already created Inventory again, but need to gave message already exists.

![Screenshot from 2023-11-23 16-46-25](https://github.com/bagisto/headless-ecommerce/assets/126852181/873e01b8-c571-4961-a79a-375cf9ed7177)

**Update Inventory Source API -** 

**Remove Inventory Source API -**

If we give the inventory ID [which does not exist] then we get an internal server error but need to get the proper message data not found on the console.

**Screenshot -**

![Screenshot from 2023-11-23 15-30-52](https://github.com/bagisto/headless-ecommerce/assets/126852181/53232eac-ea79-4c84-97b2-3ad8a841a2f9)

**Comment by rachana-webkul** [comment]
@mukulsharma-webkul  Issue is invalid

**Comment by mukulsharma-webkul** [comment]
As per discussion, We need to check the API only by entering the correct data, so I am closing the issue.

**Screenshot -**

![Screenshot from 2023-11-27 12-58-29](https://github.com/bagisto/headless-ecommerce/assets/126852181/6bcc3afc-fa76-447f-bbcc-1b5c0de4478b)
